"""Tests for the human-readable Markdown reports."""

from lreview.gerrit import ResolvedChange
from lreview.markdown import (
    markdown_filename,
    review_markdown,
    write_review_markdown,
)


def _change():
    return ResolvedChange(
        number=63809, project="fs/lustre-release",
        subject="LU-19852 lod: raidset aware stripe allocator",
        sha="a" * 40, patchset=54, ref="refs/changes/09/63809/54",
        base_url="https://review.whamcloud.com")


SPEC = {
    "tag": "autogenerated:ai-review",
    "message": "Some concerns, see inline comments.",
    "comments": {
        "lustre/lod/lod_qos.c": [
            {"line": 319, "message": "(defect) leaks the buffer",
             "unresolved": True},
            {"range": {"start_line": 10, "end_line": 12},
             "line": 12, "message": "(style) wrap this",
             "unresolved": True},
        ],
        "/COMMIT_MSG": [
            {"line": 7, "message": "(typo) subjcet", "unresolved": False},
        ],
    },
}


class TestFilename:

    def test_sanitized(self):
        name = markdown_filename(_change())
        assert name == ("63809_LU-19852_lod_raidset_aware_stripe"
                        "_allocator_ps54.md")

    def test_odd_characters(self):
        change = _change()
        change.subject = 'fix "foo/bar": 100% (really!)'
        assert markdown_filename(change) == (
            "63809_fix_foo_bar_100_really_ps54.md")


class TestReviewMarkdown:

    def test_full_render(self):
        md = review_markdown(
            _change(), SPEC, severity="high", model="opus",
            tokens=6_500_000, cost_usd=7.92, duration=1117)

        assert md.startswith(
            "# 63809 ps54 — LU-19852 lod: raidset aware stripe allocator")
        assert ("https://review.whamcloud.com/c/fs/lustre-release/+/63809"
                in md)
        assert "3 finding(s), severity **high**" in md
        assert "opus, 6.5M tokens, $7.92, 18m37s" in md
        assert "## Overall assessment" in md
        assert "Some concerns, see inline comments." in md
        assert "### 1. `lustre/lod/lod_qos.c` (line 319)" in md
        assert "(defect) leaks the buffer" in md
        assert "### 2. `lustre/lod/lod_qos.c` (lines 10–12)" in md
        assert "### 3. `/COMMIT_MSG` (line 7) *(informational)*" in md

    def test_flat_list_and_minimal_stats(self):
        spec = {"comments": [
            {"path": "a.c", "message": "file-level note"}]}
        md = review_markdown(_change(), spec)
        assert "### 1. `a.c` (file-level)" in md
        assert "**Run:**" not in md

    def test_write_creates_markdown_dir(self, tmp_path):
        path = write_review_markdown(tmp_path, _change(), SPEC,
                                     severity="high")
        assert path == (tmp_path / "markdown" /
                        markdown_filename(_change()))
        assert path.read_text().startswith("# 63809 ps54")


class TestRenderExisting:

    def _results(self, tmp_path, with_summary=True, with_metadata=False):
        import json
        d = tmp_path / "results"
        d.mkdir()
        (d / "gerrit-review-63809_ps54.json").write_text(
            json.dumps(SPEC))
        if with_summary:
            (d / "summary.json").write_text(json.dumps({"63809": {
                "number": 63809, "patchset": 54, "sha": "b" * 40,
                "subject": "LU-19852 lod: raidset aware stripe allocator",
                "base_url": "https://review.whamcloud.com",
                "severity": "high", "model": "opus",
                "tokens": 6_500_000, "cost_usd": 7.92,
                "duration_s": 1117, "status": "findings",
            }}))
        if with_metadata:
            (d / "review-metadata-63809_ps54.json").write_text(
                json.dumps({"subject": "LU-19852 from metadata",
                            "sha": "c" * 40}))
        return d

    def test_render_with_summary_stats(self, tmp_path):
        from lreview.markdown import render_existing
        d = self._results(tmp_path)
        written, skipped = render_existing(results_dir=d)
        assert skipped == []
        assert len(written) == 1
        text = written[0].read_text()
        assert "LU-19852 lod: raidset aware stripe allocator" in text
        assert "6.5M tokens, $7.92" in text
        assert written[0].parent == d / "markdown"

    def test_render_metadata_fallback(self, tmp_path):
        from lreview.markdown import render_existing
        d = self._results(tmp_path, with_summary=False,
                          with_metadata=True)
        written, _ = render_existing(results_dir=d)
        text = written[0].read_text()
        assert "LU-19852 from metadata" in text
        assert "cccccccccccc" in text

    def test_render_stale_summary_entry_ignored(self, tmp_path):
        """A summary entry for a different patchset must not lend its
        stats to this file."""
        import json
        from lreview.markdown import render_existing
        d = self._results(tmp_path, with_metadata=True)
        summary = json.loads((d / "summary.json").read_text())
        summary["63809"]["patchset"] = 55
        (d / "summary.json").write_text(json.dumps(summary))
        written, _ = render_existing(results_dir=d)
        text = written[0].read_text()
        assert "LU-19852 from metadata" in text
        assert "$7.92" not in text

    def test_render_explicit_files_and_skips(self, tmp_path):
        from lreview.markdown import render_existing
        d = self._results(tmp_path)
        odd = d / "notes.json"
        odd.write_text("{}")
        written, skipped = render_existing(
            files=[d / "gerrit-review-63809_ps54.json", odd])
        assert len(written) == 1
        assert skipped[0][0] == odd