"""Tests for posting collected results to Gerrit."""

import json
from unittest.mock import MagicMock, patch

import pytest

from lreview.poster import post_results, load_summary

REVIEW_SPEC = {
    "tag": "autogenerated:ai-review",
    "message": "Some concerns.",
    "comments": {
        "a.c": [{"line": 1, "message": "x", "unresolved": True}],
    },
}


@pytest.fixture
def results_dir(tmp_path):
    d = tmp_path / "results"
    d.mkdir()
    (d / "gerrit-review-101_ps4.json").write_text(json.dumps(REVIEW_SPEC))
    summary = {
        "101": {
            "number": 101, "patchset": 4, "sha": "a" * 40,
            "subject": "s", "base_url": "https://gerrit.invalid",
            "status": "findings", "findings": 1, "model": "fable",
            "agent": "claude",
            "json": "gerrit-review-101_ps4.json",
            "log": "kreview-101_ps4.log", "error": None, "posted": False,
        },
        "102": {
            "number": 102, "patchset": 1, "sha": "b" * 40,
            "subject": "s2", "base_url": "https://gerrit.invalid",
            "status": "clean", "findings": 0, "json": None,
            "log": "kreview-102_ps1.log", "error": None, "posted": False,
        },
    }
    (d / "summary.json").write_text(json.dumps(summary))
    return d


def _mock_reviewer(success=True):
    reviewer = MagicMock()
    result = MagicMock()
    result.success = success
    result.comments_posted = 1
    result.error = None if success else "boom"
    reviewer.post_review.return_value = result
    return reviewer


def _patched(reviewer):
    """Patch both gerrit_cli entry points the poster imports."""
    return (
        patch("gerrit_cli.reviewer.CodeReviewer", return_value=reviewer),
        patch("gerrit_cli.client.GerritCommentsClient"),
    )


class TestPostResults:

    def test_posts_findings_pinned_to_reviewed_sha(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client as mock_client:
            outcomes = post_results(results_dir, prefix="[Marc Bot]")
            # The client targets the recorded base_url, not $GERRIT_URL
            mock_client.assert_called_once_with(url="https://gerrit.invalid")

        by_number = {o.number: o for o in outcomes}
        assert by_number[101].status == "posted"
        assert by_number[102].status == "skipped"  # clean, nothing to post

        kwargs = reviewer.post_review.call_args[1]
        assert kwargs["change_number"] == 101
        assert kwargs["revision"] == "a" * 40
        assert kwargs["prefix"] == "[Marc Bot]"
        assert kwargs["tag"] == "autogenerated:ai-review"
        assert kwargs["comments"] == REVIEW_SPEC["comments"]
        assert kwargs["message"] == REVIEW_SPEC["message"]
        assert kwargs["vote"] is None

        # Manifest updated
        summary = load_summary(results_dir)
        assert summary["101"]["posted"] is True
        assert summary["101"]["posted_prefix"] == "[Marc Bot]"

    def test_review_json_cannot_vote(self, results_dir):
        """The review must not vote (review-prompts gerrit-review.md);
        a vote in the agent's JSON never reaches Gerrit."""
        (results_dir / "gerrit-review-101_ps4.json").write_text(
            json.dumps({**REVIEW_SPEC, "vote": -1}))
        with patch("gerrit_cli.client.GerritCommentsClient") as client:
            outcomes = post_results(results_dir, changes=[101])
        assert outcomes[0].status == "posted"
        body = client.return_value.rest.post.call_args[1]["json"]
        assert "labels" not in body
        assert body["comments"]["a.c"][0]["line"] == 1

    def test_review_json_cannot_choose_the_tag(self, results_dir):
        """autogenerated:ai-review is what marks the comments as
        automation, to Gerrit and to later AI reviews reading them."""
        (results_dir / "gerrit-review-101_ps4.json").write_text(
            json.dumps({**REVIEW_SPEC, "tag": "lgtm-from-a-human"}))
        with patch("gerrit_cli.client.GerritCommentsClient") as client:
            outcomes = post_results(results_dir, changes=[101])
        assert outcomes[0].status == "posted"
        body = client.return_value.rest.post.call_args[1]["json"]
        assert body["tag"] == "autogenerated:ai-review"

    def test_already_posted_skipped_unless_force(self, results_dir):
        summary = load_summary(results_dir)
        summary["101"]["posted"] = True
        (results_dir / "summary.json").write_text(json.dumps(summary))

        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            outcomes = post_results(results_dir, changes=[101])
            assert outcomes[0].status == "skipped"
            reviewer.post_review.assert_not_called()

            outcomes = post_results(results_dir, changes=[101], force=True)
            assert outcomes[0].status == "posted"
            reviewer.post_review.assert_called_once()

    def test_post_error_reported(self, results_dir):
        reviewer = _mock_reviewer(success=False)
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            outcomes = post_results(results_dir, changes=[101])
        assert outcomes[0].status == "error"
        assert "boom" in outcomes[0].detail
        summary = load_summary(results_dir)
        assert summary["101"]["posted"] is False

    def test_config_error_is_outcome_not_traceback(self, results_dir):
        p_rev = patch("gerrit_cli.reviewer.CodeReviewer",
                      side_effect=RuntimeError("no credentials"))
        p_client = patch("gerrit_cli.client.GerritCommentsClient")
        with p_rev, p_client:
            outcomes = post_results(results_dir, changes=[101])
        assert outcomes[0].status == "error"
        assert "no credentials" in outcomes[0].detail

    def test_unknown_change_raises(self, results_dir):
        with pytest.raises(KeyError):
            post_results(results_dir, changes=[999])

    def test_memory_iteration_appended_to_message(self, results_dir):
        """A -m review's posted cover message says which accumulated
        iteration it is; entries without the field post unchanged."""
        summary = load_summary(results_dir)
        summary["101"]["memory_reviews"] = 3
        (results_dir / "summary.json").write_text(json.dumps(summary))

        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[101])
        message = reviewer.post_review.call_args[1]["message"]
        assert message.startswith(REVIEW_SPEC["message"])
        assert "review iteration 3 of this change" in message

    def test_no_memory_field_message_unchanged(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[101])
        kwargs = reviewer.post_review.call_args[1]
        assert kwargs["message"] == REVIEW_SPEC["message"]

    def test_mode_tagged_entries_reachable(self, results_dir):
        """A light entry is posted via its exact key or via the bare
        change number (which expands to every mode's entry)."""
        (results_dir / "gerrit-review-103_ps2-light.json").write_text(
            json.dumps(REVIEW_SPEC))
        summary = load_summary(results_dir)
        summary["103-light"] = {
            "number": 103, "patchset": 2, "sha": "c" * 40,
            "subject": "s3", "base_url": "https://gerrit.invalid",
            "status": "findings", "findings": 1, "model": "opus",
            "agent": "claude", "mode": "light",
            "json": "gerrit-review-103_ps2-light.json",
            "log": "kreview-103_ps2-light.log", "error": None,
            "posted": False,
        }
        (results_dir / "summary.json").write_text(json.dumps(summary))

        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            outcomes = post_results(results_dir, changes=["103-light"])
        assert outcomes[0].status == "posted"
        assert reviewer.post_review.call_args[1]["change_number"] == 103

        # bare number expands to the light entry too (now already
        # posted, so it is found and guard-skipped, not missing)
        with p_rev, p_client:
            outcomes = post_results(results_dir, changes=[103])
        assert outcomes[0].status == "skipped"
        assert "already posted" in outcomes[0].detail

    def test_missing_summary_raises(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            post_results(tmp_path)

    def test_default_tag_filled_in(self, results_dir):
        spec = dict(REVIEW_SPEC)
        del spec["tag"]
        (results_dir / "gerrit-review-101_ps4.json").write_text(
            json.dumps(spec))
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[101])
        assert reviewer.post_review.call_args[1]["tag"] == (
            "autogenerated:ai-review")

    def test_default_prefix_stamped_with_model(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[101])  # no prefix given
        kwargs = reviewer.post_review.call_args[1]
        assert kwargs["prefix"] == "[AI review - fable]"
        summary = load_summary(results_dir)
        assert summary["101"]["posted_prefix"] == "[AI review - fable]"

    def test_default_prefix_without_model_falls_back_to_agent(
            self, results_dir):
        summary = load_summary(results_dir)
        del summary["101"]["model"]
        (results_dir / "summary.json").write_text(json.dumps(summary))

        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[101])
        assert reviewer.post_review.call_args[1]["prefix"] == (
            "[AI review - claude]")

    def test_custom_prefix_model_placeholder(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[101],
                         prefix="[Marc Bot - AI review - <model>]")
        assert reviewer.post_review.call_args[1]["prefix"] == (
            "[Marc Bot - AI review - fable]")

    def test_custom_prefix_without_placeholder_verbatim(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[101], prefix="[Marc Bot]")
        assert reviewer.post_review.call_args[1]["prefix"] == "[Marc Bot]"

    def test_empty_prefix_means_no_prefix(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[101], prefix="")
        assert reviewer.post_review.call_args[1]["prefix"] == ""

    def test_local_entries_never_posted(self, results_dir):
        summary = load_summary(results_dir)
        summary["mybranch_abc1234"] = {
            "number": None, "local": True, "ref_name": "mybranch",
            "patchset": None, "sha": "c" * 40, "subject": "s",
            "base_url": "", "status": "findings", "findings": 2,
            "json": "gerrit-review-mybranch_abc1234.json",
            "posted": False,
        }
        (results_dir / "summary.json").write_text(json.dumps(summary))

        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            outcomes = post_results(results_dir)  # post everything
        local = [o for o in outcomes if o.number == "mybranch_abc1234"]
        assert local[0].status == "skipped"
        assert "local review" in local[0].detail
        # the gerrit entry still posts normally
        assert any(o.status == "posted" and o.number == 101
                   for o in outcomes)

    def test_guard_rechecks_manifest_under_lock(self, results_dir):
        """A concurrent poster marking the entry posted between our
        snapshot and the per-entry lock must be respected."""
        reviewer = _mock_reviewer()

        def mark_posted_then_return(*args, **kwargs):
            raise AssertionError("post_review must not be called")

        reviewer.post_review.side_effect = mark_posted_then_return

        # Simulate the concurrent post by marking posted AFTER the
        # initial snapshot would have been taken: patch load path is
        # not needed — post_results re-reads under the lock, so a
        # pre-marked manifest with a stale snapshot is equivalent.
        summary = load_summary(results_dir)
        summary["101"]["posted"] = True
        (results_dir / "summary.json").write_text(json.dumps(summary))

        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            outcomes = post_results(results_dir, changes=[101])
        assert outcomes[0].status == "skipped"


class TestDryRun:
    """--dry-run shares post_results' selection, so what it lists is
    what a real post would send."""

    def test_honours_the_change_filter(self, results_dir):
        """The bug this replaced listed every entry in the results
        dir, whatever change was asked for."""
        (results_dir / "gerrit-review-103_ps2.json").write_text(
            json.dumps(REVIEW_SPEC))
        summary = load_summary(results_dir)
        summary["103"] = {
            "number": 103, "patchset": 2, "sha": "c" * 40,
            "subject": "s3", "base_url": "https://gerrit.invalid",
            "status": "findings", "findings": 1, "model": "opus",
            "agent": "claude", "json": "gerrit-review-103_ps2.json",
            "log": "kreview-103_ps2.log", "error": None, "posted": False,
        }
        (results_dir / "summary.json").write_text(json.dumps(summary))

        outcomes = post_results(results_dir, changes=[101], dry_run=True)
        assert [o.number for o in outcomes] == [101]
        assert outcomes[0].status == "would post"
        assert "1 comment(s) on ps4" in outcomes[0].detail

    def test_contacts_no_provider_and_leaves_manifest_alone(
            self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client as mock_client:
            post_results(results_dir, changes=[101], dry_run=True)
        reviewer.post_review.assert_not_called()
        mock_client.assert_not_called()
        assert load_summary(results_dir)["101"]["posted"] is False

    def test_applies_the_same_guards_as_a_real_post(self, results_dir):
        summary = load_summary(results_dir)
        summary["mybranch_abc1234"] = {
            "number": None, "local": True, "ref_name": "mybranch",
            "patchset": None, "sha": "c" * 40, "subject": "s",
            "base_url": "", "status": "findings", "findings": 2,
            "json": "gerrit-review-mybranch_abc1234.json",
            "posted": False,
        }
        (results_dir / "summary.json").write_text(json.dumps(summary))

        outcomes = post_results(results_dir, dry_run=True)
        by_key = {o.number: o for o in outcomes}
        assert by_key[101].status == "would post"
        assert by_key[102].status == "skipped"       # clean
        assert by_key["mybranch_abc1234"].status == "skipped"  # local

    def test_already_posted_shown_unless_force(self, results_dir):
        summary = load_summary(results_dir)
        summary["101"]["posted"] = True
        (results_dir / "summary.json").write_text(json.dumps(summary))

        outcomes = post_results(results_dir, changes=[101], dry_run=True)
        assert outcomes[0].status == "skipped"
        assert "already posted" in outcomes[0].detail

        outcomes = post_results(results_dir, changes=[101], force=True,
                                dry_run=True)
        assert outcomes[0].status == "would post"
        assert load_summary(results_dir)["101"]["posted"] is True

    def test_unknown_change_raises(self, results_dir):
        with pytest.raises(KeyError):
            post_results(results_dir, changes=[999], dry_run=True)

    def test_github_reports_what_the_post_sends(self, results_dir,
                                                monkeypatch):
        """Only inline findings become GitHub review comments; general
        and commit-message findings go into the review body."""
        name = f"review-result-github_acme_widget_7_{'b' * 7}.json"
        (results_dir / name).write_text(json.dumps({
            "version": 1, "message": "m", "findings": [
                {"path": "src.c", "line": 2, "message": "inline one"},
                {"location_kind": "summary", "path": None, "line": None,
                 "message": "general one"},
                {"location_kind": "commit_message", "path": None,
                 "line": None, "message": "subject one"}]}))
        summary = load_summary(results_dir)
        key = "github:acme/widget#7"
        summary[key] = {
            "provider": "github", "number": 7, "patchset": None,
            "sha": "b" * 40, "head_sha": "b" * 40,
            "repository": "acme/widget", "status": "findings",
            "findings": 3, "model": "opus", "json": name, "posted": False,
        }
        (results_dir / "summary.json").write_text(json.dumps(summary))
        expected = (f"1 inline comment(s) pinned to {'b' * 12}, "
                    "2 more finding(s) in the review body")

        dry, = post_results(results_dir, changes=[key], dry_run=True)
        assert (dry.status, dry.detail) == ("would post", expected)

        sent = []

        def fake_request(path, method="GET", data=None, token=None):
            if method == "GET":
                return {"head": {"sha": "b" * 40}}
            sent.append(data)
            return {}

        monkeypatch.setattr("lreview.github.github_request", fake_request)
        real, = post_results(results_dir, changes=[key])
        assert (real.status, real.detail) == ("posted", f"posted {expected}")
        assert [c["body"] for c in sent[0]["comments"]] == ["inline one"]
        assert "general one" in sent[0]["body"]
        assert "subject one" in sent[0]["body"]


class TestCleanReviews:
    """A clean Gerrit review posts a no-issues message when named; a
    bare `post` leaves it alone, since every unposted clean entry in
    the manifest would otherwise get one, however old."""

    def test_named_clean_posts_a_no_issues_message(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            outcomes = post_results(results_dir, changes=[102])
        assert outcomes[0].status == "posted"
        assert "no-issues message on ps1" in outcomes[0].detail

        kwargs = reviewer.post_review.call_args[1]
        assert kwargs["change_number"] == 102
        assert kwargs["revision"] == "b" * 40
        assert kwargs["message"] == (
            "Looks good: the review found no issues in ps1.")
        assert kwargs["comments"] is None
        assert kwargs["vote"] is None
        assert kwargs["tag"] == "autogenerated:ai-review"
        assert load_summary(results_dir)["102"]["posted"] is True

    def test_double_post_guarded(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[102])
            outcomes = post_results(results_dir, changes=[102])
        assert outcomes[0].status == "skipped"
        assert "already posted" in outcomes[0].detail
        reviewer.post_review.assert_called_once()

    def test_bare_post_skips_clean_and_says_how(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            outcomes = post_results(results_dir)
        by_number = {o.number: o for o in outcomes}
        assert by_number[101].status == "posted"
        assert by_number[102].status == "skipped"
        assert "lreview post 102" in by_number[102].detail
        assert reviewer.post_review.call_count == 1
        assert load_summary(results_dir)["102"]["posted"] is False

    def test_light_mode_and_memory_iteration(self, results_dir):
        summary = load_summary(results_dir)
        summary["102-light"] = dict(
            summary.pop("102"), mode="light", memory_reviews=2)
        (results_dir / "summary.json").write_text(json.dumps(summary))
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=["102-light"])
        message = reviewer.post_review.call_args[1]["message"]
        assert message.startswith(
            "Looks good: the light review found no issues in ps1.")
        assert "review iteration 2 of this change" in message

    def test_dry_run_describes_the_message(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            outcomes = post_results(results_dir, changes=[102],
                                    dry_run=True)
        assert outcomes[0].status == "would post"
        assert outcomes[0].detail == "no-issues message on ps1"
        reviewer.post_review.assert_not_called()

    def test_local_and_failed_still_never_post(self, results_dir):
        summary = load_summary(results_dir)
        summary["HEAD_abc1234"] = {
            "number": None, "local": True, "status": "clean",
            "sha": "d" * 40, "patchset": None, "posted": False}
        summary["104"] = {
            "number": 104, "patchset": 3, "sha": "e" * 40,
            "status": "failed", "json": None, "posted": False}
        (results_dir / "summary.json").write_text(json.dumps(summary))
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            outcomes = post_results(results_dir,
                                    changes=["HEAD_abc1234", 104])
        assert [o.status for o in outcomes] == ["skipped", "skipped"]
        assert "status is 'failed'" in outcomes[1].detail
        reviewer.post_review.assert_not_called()
