"""Tests for posting collected results to Gerrit."""

import json
from unittest.mock import MagicMock, patch

import pytest

from lreview.poster import post_results, load_summary

REVIEW_SPEC = {
    "tag": "autogenerated:ai-review",
    "message": "Some concerns.",
    "comments": {
        "a.c": [{"line": 1, "message": "x", "unresolved": True}],
    },
}


@pytest.fixture
def results_dir(tmp_path):
    d = tmp_path / "results"
    d.mkdir()
    (d / "gerrit-review-101_ps4.json").write_text(json.dumps(REVIEW_SPEC))
    summary = {
        "101": {
            "number": 101, "patchset": 4, "sha": "a" * 40,
            "subject": "s", "base_url": "https://gerrit.invalid",
            "status": "findings", "findings": 1, "model": "fable",
            "agent": "claude",
            "json": "gerrit-review-101_ps4.json",
            "log": "kreview-101_ps4.log", "error": None, "posted": False,
        },
        "102": {
            "number": 102, "patchset": 1, "sha": "b" * 40,
            "subject": "s2", "base_url": "https://gerrit.invalid",
            "status": "clean", "findings": 0, "json": None,
            "log": "kreview-102_ps1.log", "error": None, "posted": False,
        },
    }
    (d / "summary.json").write_text(json.dumps(summary))
    return d


def _mock_reviewer(success=True):
    reviewer = MagicMock()
    result = MagicMock()
    result.success = success
    result.comments_posted = 1
    result.error = None if success else "boom"
    reviewer.post_review.return_value = result
    return reviewer


def _patched(reviewer):
    """Patch both gerrit_cli entry points the poster imports."""
    return (
        patch("gerrit_cli.reviewer.CodeReviewer", return_value=reviewer),
        patch("gerrit_cli.client.GerritCommentsClient"),
    )


class TestPostResults:

    def test_posts_findings_pinned_to_reviewed_sha(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client as mock_client:
            outcomes = post_results(results_dir, prefix="[Marc Bot]")
            # The client targets the recorded base_url, not $GERRIT_URL
            mock_client.assert_called_once_with(url="https://gerrit.invalid")

        by_number = {o.number: o for o in outcomes}
        assert by_number[101].status == "posted"
        assert by_number[102].status == "skipped"  # clean, nothing to post

        kwargs = reviewer.post_review.call_args[1]
        assert kwargs["change_number"] == 101
        assert kwargs["revision"] == "a" * 40
        assert kwargs["prefix"] == "[Marc Bot]"
        assert kwargs["tag"] == "autogenerated:ai-review"
        assert kwargs["comments"] == REVIEW_SPEC["comments"]
        assert kwargs["message"] == REVIEW_SPEC["message"]
        assert kwargs["vote"] is None

        # Manifest updated
        summary = load_summary(results_dir)
        assert summary["101"]["posted"] is True
        assert summary["101"]["posted_prefix"] == "[Marc Bot]"

    def test_already_posted_skipped_unless_force(self, results_dir):
        summary = load_summary(results_dir)
        summary["101"]["posted"] = True
        (results_dir / "summary.json").write_text(json.dumps(summary))

        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            outcomes = post_results(results_dir, changes=[101])
            assert outcomes[0].status == "skipped"
            reviewer.post_review.assert_not_called()

            outcomes = post_results(results_dir, changes=[101], force=True)
            assert outcomes[0].status == "posted"
            reviewer.post_review.assert_called_once()

    def test_post_error_reported(self, results_dir):
        reviewer = _mock_reviewer(success=False)
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            outcomes = post_results(results_dir, changes=[101])
        assert outcomes[0].status == "error"
        assert "boom" in outcomes[0].detail
        summary = load_summary(results_dir)
        assert summary["101"]["posted"] is False

    def test_config_error_is_outcome_not_traceback(self, results_dir):
        p_rev = patch("gerrit_cli.reviewer.CodeReviewer",
                      side_effect=RuntimeError("no credentials"))
        p_client = patch("gerrit_cli.client.GerritCommentsClient")
        with p_rev, p_client:
            outcomes = post_results(results_dir, changes=[101])
        assert outcomes[0].status == "error"
        assert "no credentials" in outcomes[0].detail

    def test_unknown_change_raises(self, results_dir):
        with pytest.raises(KeyError):
            post_results(results_dir, changes=[999])

    def test_missing_summary_raises(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            post_results(tmp_path)

    def test_default_tag_filled_in(self, results_dir):
        spec = dict(REVIEW_SPEC)
        del spec["tag"]
        (results_dir / "gerrit-review-101_ps4.json").write_text(
            json.dumps(spec))
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[101])
        assert reviewer.post_review.call_args[1]["tag"] == (
            "autogenerated:ai-review")

    def test_default_prefix_stamped_with_model(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[101])  # no prefix given
        kwargs = reviewer.post_review.call_args[1]
        assert kwargs["prefix"] == "[AI review - fable]"
        summary = load_summary(results_dir)
        assert summary["101"]["posted_prefix"] == "[AI review - fable]"

    def test_default_prefix_without_model_falls_back_to_agent(
            self, results_dir):
        summary = load_summary(results_dir)
        del summary["101"]["model"]
        (results_dir / "summary.json").write_text(json.dumps(summary))

        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[101])
        assert reviewer.post_review.call_args[1]["prefix"] == (
            "[AI review - claude]")

    def test_custom_prefix_model_placeholder(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[101],
                         prefix="[Marc Bot - AI review - <model>]")
        assert reviewer.post_review.call_args[1]["prefix"] == (
            "[Marc Bot - AI review - fable]")

    def test_custom_prefix_without_placeholder_verbatim(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[101], prefix="[Marc Bot]")
        assert reviewer.post_review.call_args[1]["prefix"] == "[Marc Bot]"

    def test_empty_prefix_means_no_prefix(self, results_dir):
        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            post_results(results_dir, changes=[101], prefix="")
        assert reviewer.post_review.call_args[1]["prefix"] == ""

    def test_local_entries_never_posted(self, results_dir):
        summary = load_summary(results_dir)
        summary["mybranch_abc1234"] = {
            "number": None, "local": True, "ref_name": "mybranch",
            "patchset": None, "sha": "c" * 40, "subject": "s",
            "base_url": "", "status": "findings", "findings": 2,
            "json": "gerrit-review-mybranch_abc1234.json",
            "posted": False,
        }
        (results_dir / "summary.json").write_text(json.dumps(summary))

        reviewer = _mock_reviewer()
        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            outcomes = post_results(results_dir)  # post everything
        local = [o for o in outcomes if o.number == "mybranch_abc1234"]
        assert local[0].status == "skipped"
        assert "local review" in local[0].detail
        # the gerrit entry still posts normally
        assert any(o.status == "posted" and o.number == 101
                   for o in outcomes)

    def test_guard_rechecks_manifest_under_lock(self, results_dir):
        """A concurrent poster marking the entry posted between our
        snapshot and the per-entry lock must be respected."""
        reviewer = _mock_reviewer()

        def mark_posted_then_return(*args, **kwargs):
            raise AssertionError("post_review must not be called")

        reviewer.post_review.side_effect = mark_posted_then_return

        # Simulate the concurrent post by marking posted AFTER the
        # initial snapshot would have been taken: patch load path is
        # not needed — post_results re-reads under the lock, so a
        # pre-marked manifest with a stale snapshot is equivalent.
        summary = load_summary(results_dir)
        summary["101"]["posted"] = True
        (results_dir / "summary.json").write_text(json.dumps(summary))

        p_rev, p_client = _patched(reviewer)
        with p_rev, p_client:
            outcomes = post_results(results_dir, changes=[101])
        assert outcomes[0].status == "skipped"
