"""Offline end-to-end tests for the batch runner.

A stub `claude` executable is placed on PATH; its behavior is driven by
marker files committed in the test repository, so the whole pipeline
(worktree creation, parallel execution, collection, summary manifest,
worktree cleanup) runs for real without network or a real Claude.
"""

import json
import os
import stat
import subprocess
from pathlib import Path

import pytest

from lreview.gerrit import ResolvedChange, change_ref
from lreview.runner import (
    CLOSING_NOTE,
    BatchConfig,
    STATUS_CLEAN,
    STATUS_FAILED,
    STATUS_FINDINGS,
    STATUS_INVALID_JSON,
    STATUS_TIMEOUT,
    build_agent_cmd,
    count_findings,
    run_batch,
    update_summary,
)

REVIEW_SPEC = {
    "tag": "autogenerated:ai-review",
    "message": "Some concerns.",
    "comments": {
        "a.c": [{"line": 1, "message": "x", "unresolved": True}],
        "b.c": [{"line": 2, "message": "y", "unresolved": True},
                {"line": 3, "message": "z", "unresolved": True}],
    },
}

# Behavior is driven by marker files in the worktree (cwd). A completed
# analysis always writes review-metadata.json (as review-core.md
# mandates); NO_METADATA simulates a claude run that bailed out early.
STUB_CLAUDE = """#!/bin/bash
if [ -n "$STUB_ARGS_LOG" ]; then printf '%s\\n' "$@" -- >> "$STUB_ARGS_LOG"; fi
case " $* " in *" --resume "*)
    if [ -n "$STUB_NO_SESSION" ]; then
        echo "No conversation found with session ID: gone" >&2; exit 1
    fi;;
esac
echo '{"type":"system","subtype":"init","session_id":"'"${STUB_SESSION:-sess-1}"'"}'
if [ -f FAIL_MARKER ]; then echo "boom"; exit 3; fi
if [ -f SLEEP_MARKER ]; then sleep 30; exit 0; fi
if [ -f NO_METADATA_MARKER ]; then echo "bailed early"; exit 0; fi
SEV=none
if [ -f HAS_FINDINGS ]; then SEV=high; fi
printf '{"author":"a","sha":"s","subject":"t","issues-found":0,\
"issue-severity-score":"%s","issue-severity-explanation":"e"}' "$SEV" \
    > review-metadata.json
if [ -f INVALID_MARKER ]; then printf '{oops' > gerrit-review.json; exit 0; fi
if [ -f ARRAY_MARKER ]; then printf '[]' > gerrit-review.json; exit 0; fi
if [ -f HAS_FINDINGS ]; then cp HAS_FINDINGS gerrit-review.json; fi
if [ -f RESULT_MARKER ]; then cp RESULT_MARKER review-result.json; fi
echo '{"type":"system","subtype":"estimated_tokens","estimated_tokens":123456}'
echo "Assisted-by: ClaudeCode:claude-fable-5"
echo '{"type":"result","result":"done","total_cost_usd":1.23,"usage":{"input_tokens":10,"cache_creation_input_tokens":1000,"cache_read_input_tokens":50000,"output_tokens":2000}}'
"""


def _git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args], capture_output=True, text=True)
    assert result.returncode == 0, result.stderr
    return result.stdout.strip()


@pytest.fixture
def stub_claude(tmp_path, monkeypatch):
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    stub = bin_dir / "claude"
    stub.write_text(STUB_CLAUDE)
    stub.chmod(stub.stat().st_mode | stat.S_IEXEC)
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{os.environ['PATH']}")
    return stub


@pytest.fixture
def repo(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-q")
    _git(repo, "config", "user.email", "t@example.com")
    _git(repo, "config", "user.name", "Test")
    (repo / "base.txt").write_text("base\n")
    _git(repo, "add", ".")
    _git(repo, "commit", "-q", "-m", "base")
    return repo


def _commit_with_marker(repo: Path, name: str, content: str = "") -> str:
    """Create a commit adding a marker file; return its SHA."""
    _git(repo, "checkout", "-q", "--detach", "HEAD")
    marker = repo / name
    marker.write_text(content)
    _git(repo, "add", name)
    _git(repo, "commit", "-q", "-m", f"add {name}")
    sha = _git(repo, "rev-parse", "HEAD")
    _git(repo, "rm", "-q", name)
    _git(repo, "commit", "-q", "-m", f"remove {name}")
    return sha


def _change(number: int, sha: str) -> ResolvedChange:
    return ResolvedChange(
        number=number, project="test/repo", subject=f"change {number}",
        sha=sha, patchset=1, ref=change_ref(number, 1),
        base_url="https://gerrit.invalid")


GITHUB_RESULT = {
    "version": 1,
    "message": "Some concerns.",
    "findings": [
        {"path": "src.c", "line": 2, "message": "b is unused",
         "unresolved": True},
        {"location_kind": "summary", "path": None, "line": None,
         "message": "needs a test"},
    ],
}


def _github_pr(repo: Path, files: dict):
    """A pull request whose head commit adds `files` on top of HEAD."""
    from lreview.github import ResolvedGitHubPullRequest
    base = _git(repo, "rev-parse", "HEAD")
    for name, content in files.items():
        (repo / name).write_text(content)
        _git(repo, "add", name)
    _git(repo, "commit", "-q", "-m", "PR head")
    head = _git(repo, "rev-parse", "HEAD")
    return ResolvedGitHubPullRequest(
        "acme", "widget", 7, "Fix the widget", head, base, "fix",
        "acme/widget", "https://github.com/acme/widget/pull/7")


def _config(repo: Path, tmp_path: Path, **kwargs) -> BatchConfig:
    return BatchConfig(
        repo=repo,
        results_dir=tmp_path / "results",
        worktrees_dir=tmp_path / "worktrees",
        **kwargs,
    )


class TestBuildAgentCmd:

    def test_default(self, tmp_path):
        config = _config(tmp_path, tmp_path,
                         prompts_dir=Path("/p/kernel"))
        cmd = build_agent_cmd(config)
        assert cmd[:2] == ["claude", "-p"]
        assert cmd[2] == ("Using the prompt /p/kernel/review-core.md "
                          "run a deep dive regression analysis of the "
                          "top commit.\n\n" + CLOSING_NOTE)
        assert cmd[3:] == ["--dangerously-skip-permissions",
                           "--verbose", "--output-format", "stream-json"]

    def test_model_and_extra_args(self, tmp_path):
        config = _config(tmp_path, tmp_path, model="opus",
                         agent_args=["--max-turns", "50"])
        cmd = build_agent_cmd(config)
        assert cmd[-4:] == ["--model", "opus", "--max-turns", "50"]

    def test_jobs_must_be_positive(self, tmp_path):
        with pytest.raises(ValueError):
            _config(tmp_path, tmp_path, jobs=0)

    def test_codex_model_and_effort(self, tmp_path):
        config = _config(tmp_path, tmp_path, agent="codex",
                         model="gpt-5.6-sol", effort="medium")
        cmd = build_agent_cmd(config)
        assert cmd[:6] == ["codex", "exec", "--json",
                           "--dangerously-bypass-approvals-and-sandbox",
                           "--disable", "fast_mode"]
        assert cmd[6:10] == ["-m", "gpt-5.6-sol",
                            "-c", 'model_reasoning_effort="medium"']

    def test_impossible_effort_rejected_before_any_review(self, tmp_path):
        # gpt-5.6-luna has no "ultra" rung; codex would only fail once
        # the worktree was built and the agent was running.
        with pytest.raises(ValueError, match="gpt-5.6-luna"):
            _config(tmp_path, tmp_path, agent="codex",
                    model="gpt-5.6-luna", effort="ultra")
        _config(tmp_path, tmp_path, agent="codex",
                model="gpt-5.6-sol", effort="ultra")

    def test_light_mode_prompt(self, tmp_path):
        from lreview.runner import LIGHT_PROMPT_PATH
        config = _config(tmp_path, tmp_path, mode="light",
                         prompts_dir=Path("/p/kernel"))
        cmd = build_agent_cmd(config)
        assert cmd[2] == (f"Using the prompt {LIGHT_PROMPT_PATH} run a "
                          "light regression review of the top commit; "
                          "the review-prompts knowledge directory is "
                          "/p/kernel")
        assert LIGHT_PROMPT_PATH.is_file()  # ships as package data
        assert "lustre-style.md" in LIGHT_PROMPT_PATH.read_text()

    def test_light_mode_prompt_with_memory(self, tmp_path):
        from lreview.runner import review_prompt
        config = _config(tmp_path, tmp_path, mode="light",
                         memory_db=tmp_path / "db")
        sha = "c" * 40
        prompt = review_prompt(config, _change(130, sha))
        assert "light regression review" in prompt
        assert "your review memory document" in prompt

    def test_light_memory_local_composition(self, tmp_path):
        """--mode light + -m + a local change compose: light driver,
        memory instructions, and the commit-keyed doc all appear."""
        from lreview.gerrit import LocalChange
        from lreview.runner import review_prompt
        config = _config(tmp_path, tmp_path, mode="light",
                         memory_db=tmp_path / "db")
        change = LocalChange(
            ref_name="my-branch", sha="d" * 40,
            subject="LU-1 lod: wip",
            change_id="I" + "e" * 39)
        prompt = review_prompt(config, change)
        assert "light regression review" in prompt
        assert "your review memory document" in prompt
        # locals have no patchset — the delta anchor is the commit
        assert f"reviewing commit {'d' * 12}" in prompt
        # doc created, keyed by the commit's Change-Id
        docs = list((tmp_path / "db").glob("I*.md"))
        assert len(docs) == 1
        assert change.change_id in docs[0].read_text()

    def test_unknown_mode_rejected(self, tmp_path):
        with pytest.raises(ValueError):
            _config(tmp_path, tmp_path, mode="medium")


class TestModelDetection:

    def test_configured_model_wins(self, tmp_path):
        from lreview.runner import detect_model
        log = tmp_path / "x.log"
        log.write_text("Assisted-by: ClaudeCode:claude-opus-4-8\n")
        assert detect_model(log, configured="fable") == "fable"
        assert detect_model(log, configured="claude-sonnet-5") == "sonnet"

    def test_parsed_from_assisted_by_line(self, tmp_path):
        from lreview.runner import detect_model
        log = tmp_path / "x.log"
        log.write_text(
            "review text\nAssisted-by: ClaudeCode:claude-opus-4-8\ndone\n")
        assert detect_model(log) == "opus"

    def test_parsed_from_stream_json_init_event(self, tmp_path):
        from lreview.runner import detect_model
        log = tmp_path / "x.log"
        log.write_text(
            '{"type":"system","subtype":"init","cwd":"/x",'
            '"model":"claude-fable-5","tools":[]}\n'
            '{"type":"result","result":"all good"}\n')
        assert detect_model(log) == "fable"

    def test_unknown_model_uses_tail(self, tmp_path):
        from lreview.runner import detect_model
        log = tmp_path / "x.log"
        log.write_text("Assisted-by: SomeAgent:custom-model-x\n")
        assert detect_model(log) == "custom-model-x"

    def test_no_log_no_model(self, tmp_path):
        from lreview.runner import detect_model
        assert detect_model(None) is None
        assert detect_model(tmp_path / "missing.log") is None
        log = tmp_path / "empty.log"
        log.write_text("no marker here\n")
        assert detect_model(log) is None


class TestProgressTracker:

    def test_status_line(self, tmp_path):
        from lreview.runner import ProgressTracker
        log = tmp_path / "kreview-64086_ps40.log"
        log.write_text("x" * 2048)

        tracker = ProgressTracker(total=3)
        assert tracker.status_line() is None  # nothing running yet

        tracker.start("64086_ps40", log)
        tracker.start("64087_ps12", tmp_path / "missing.log")
        line = tracker.status_line()
        assert "64086_ps40 0m00s 2KB" in line
        assert "64087_ps12 0m00s" in line
        assert "done 0/3" in line

        tracker.finish("64086_ps40")
        line = tracker.status_line()
        assert "64086_ps40" not in line
        assert "done 1/3" in line

        tracker.finish("64087_ps12")
        assert tracker.status_line() is None

    def test_status_line_shows_live_tokens(self, tmp_path):
        from lreview.runner import ProgressTracker
        log = tmp_path / "kreview-64086_ps40.log"
        log.write_text(
            '{"type":"system","subtype":"estimated_tokens",'
            '"estimated_tokens":1000}\n'
            '{"type":"system","subtype":"estimated_tokens",'
            '"estimated_tokens":842000}\n')
        tracker = ProgressTracker(total=1)
        tracker.start("64086_ps40", log)
        assert "64086_ps40 0m00s 842k tok" in tracker.status_line()


class TestTokenParsing:

    def test_format_tokens(self):
        from lreview.runner import format_tokens
        assert format_tokens(None) is None
        assert format_tokens(999) == "999"
        assert format_tokens(53010) == "53k"
        assert format_tokens(2_140_000) == "2.1M"

    def test_live_token_count_sums_usage_events(self, tmp_path):
        """The live counter sums per-message usage, deduplicated by
        message id (later lines for the same id win)."""
        from lreview.runner import live_token_count
        log = tmp_path / "usage.log"
        log.write_text(
            '{"type":"assistant","message":{"id":"m1","usage":'
            '{"input_tokens":4,"cache_creation_input_tokens":100,'
            '"cache_read_input_tokens":1000,"output_tokens":1}}}\n'
            '{"type":"assistant","message":{"id":"m1","usage":'
            '{"input_tokens":4,"cache_creation_input_tokens":100,'
            '"cache_read_input_tokens":1000,"output_tokens":50}}}\n'
            '{"type":"assistant","message":{"id":"m2","usage":'
            '{"input_tokens":2,"cache_creation_input_tokens":0,'
            '"cache_read_input_tokens":2000,"output_tokens":10}}}\n'
            'not json at all\n')
        # m1 counted once (last wins): 4+100+1000+50, m2: 2+0+2000+10
        assert live_token_count(log) == 1154 + 2012

    def test_live_token_count_latest_wins(self, tmp_path):
        from lreview.runner import live_token_count
        log = tmp_path / "x.log"
        log.write_text(
            '{"type":"system","subtype":"estimated_tokens",'
            '"estimated_tokens":1000,"estimated_tokens_delta":10}\n'
            '{"type":"assistant","message":{}}\n'
            '{"type":"system","subtype":"estimated_tokens",'
            '"estimated_tokens":84200,"estimated_tokens_delta":20}\n')
        assert live_token_count(log) == 84200
        assert live_token_count(tmp_path / "missing.log") is None

    def test_parse_final_usage(self, tmp_path):
        from lreview.runner import parse_final_usage
        log = tmp_path / "x.log"
        log.write_text(
            '{"type":"system","subtype":"init"}\n'
            '{"type":"result","total_cost_usd":4.2,"usage":'
            '{"input_tokens":5,"cache_creation_input_tokens":100,'
            '"cache_read_input_tokens":900,"output_tokens":45}}\n')
        tokens, cost = parse_final_usage(log)
        assert tokens == 1050
        assert cost == 4.2

    def test_parse_final_usage_codex_turn_completed(self, tmp_path):
        """codex reports usage once, at the end of the turn; its
        input_tokens already include the cached ones, so the total is
        input + output (13064 here, not 23048)."""
        from lreview.runner import parse_final_usage
        log = tmp_path / "x.log"
        log.write_text(
            "Reading additional input from stdin...\n"
            '{"type":"thread.started","thread_id":"01a0"}\n'
            '{"type":"turn.started"}\n'
            '{"type":"item.completed","item":{"id":"item_0",'
            '"type":"agent_message","text":"done"}}\n'
            '{"type":"turn.completed","usage":{"input_tokens":12914,'
            '"cached_input_tokens":9984,"cache_write_input_tokens":0,'
            '"output_tokens":150,"reasoning_output_tokens":0}}\n')
        tokens, cost = parse_final_usage(log)
        assert tokens == 13064
        # a ChatGPT-plan run has no dollar figure to report
        assert cost is None

    def test_live_token_count_falls_back_to_codex_usage(self, tmp_path):
        """No per-message usage during a codex run — the total shows up
        only once turn.completed lands."""
        from lreview.runner import live_token_count
        log = tmp_path / "x.log"
        log.write_text('{"type":"item.completed","item":{"id":"item_0",'
                       '"type":"command_execution"}}\n')
        assert live_token_count(log) is None
        with open(log, "a") as f:
            f.write('{"type":"turn.completed","usage":'
                    '{"input_tokens":900,"cached_input_tokens":800,'
                    '"output_tokens":100}}\n')
        assert live_token_count(log) == 1000

    def test_parse_final_usage_absent(self, tmp_path):
        from lreview.runner import parse_final_usage
        log = tmp_path / "x.log"
        log.write_text("plain text log with no result event\n")
        assert parse_final_usage(log) == (None, None)
        assert parse_final_usage(tmp_path / "missing.log") == (None, None)


class TestCountFindings:

    def test_dict_format(self):
        assert count_findings(REVIEW_SPEC) == 3

    def test_flat_list(self):
        assert count_findings({"comments": [{"path": "a", "line": 1,
                                             "message": "m"}]}) == 1

    def test_empty(self):
        assert count_findings({}) == 0


class TestRunBatch:

    def test_findings_clean_failed_invalid(self, repo, tmp_path, stub_claude):
        sha_findings = _commit_with_marker(
            repo, "HAS_FINDINGS", json.dumps(REVIEW_SPEC))
        sha_clean = _git(repo, "rev-parse", "HEAD")
        sha_failed = _commit_with_marker(repo, "FAIL_MARKER")
        sha_invalid = _commit_with_marker(repo, "INVALID_MARKER")

        changes = [
            _change(101, sha_findings),
            _change(102, sha_clean),
            _change(103, sha_failed),
            _change(104, sha_invalid),
        ]
        config = _config(repo, tmp_path, jobs=4)
        results = {r.change.number: r for r in run_batch(config, changes)}

        assert results[101].status == STATUS_FINDINGS
        assert results[101].findings == 3
        assert results[101].severity == "high"
        assert results[101].model == "fable"  # parsed from Assisted-by
        assert results[101].tokens == 53010   # from the result event
        assert results[101].cost_usd == 1.23
        assert results[102].status == STATUS_CLEAN
        assert results[102].severity == "none"
        assert results[103].status == STATUS_FAILED
        assert results[104].status == STATUS_INVALID_JSON

        # Collected artifacts are per-change suffixed and valid
        collected = config.results_dir / "gerrit-review-101_ps1.json"
        assert json.loads(collected.read_text()) == REVIEW_SPEC
        # Human-readable markdown report generated for findings
        md = config.results_dir / "markdown" / "101_change_101_ps1.md"
        assert md.is_file()
        assert "## Findings" in md.read_text()
        assert results[101].markdown_path == md
        # A clean review gets a report saying so, too
        md_clean = config.results_dir / "markdown" / "102_change_102_ps1.md"
        assert md_clean.is_file()
        assert "clean — no findings" in md_clean.read_text()
        assert results[102].markdown_path == md_clean
        metadata = config.results_dir / "review-metadata-101_ps1.json"
        assert json.loads(
            metadata.read_text())["issue-severity-score"] == "high"
        # Invalid output is preserved for debugging
        assert (config.results_dir / "gerrit-review-104_ps1.invalid").exists()
        # Logs exist per change
        assert list(config.results_dir.glob("kreview-103_ps1-*.log"))

        # Worktrees were cleaned up
        assert not any((tmp_path / "worktrees").glob("kreview_*"))

        # Summary manifest records everything
        summary = json.loads(
            (config.results_dir / "summary.json").read_text())
        assert summary["101"]["status"] == STATUS_FINDINGS
        assert summary["101"]["findings"] == 3
        assert summary["101"]["severity"] == "high"
        assert summary["101"]["model"] == "fable"
        assert summary["101"]["tokens"] == 53010
        assert summary["101"]["cost_usd"] == 1.23
        assert summary["101"]["markdown"] == "markdown/101_change_101_ps1.md"
        assert summary["101"]["sha"] == sha_findings
        assert summary["101"]["posted"] is False
        assert summary["102"]["status"] == STATUS_CLEAN
        assert summary["102"]["markdown"] == "markdown/102_change_102_ps1.md"
        assert summary["103"]["error"] == "claude exited 3"

    def test_light_mode_namespaced_artifacts(self, repo, tmp_path,
                                             stub_claude):
        """Light-mode artifacts carry a -light suffix everywhere, so a
        light run never overwrites or supersedes a full run's results
        for the same change+patchset."""
        sha = _commit_with_marker(
            repo, "HAS_FINDINGS", json.dumps(REVIEW_SPEC))
        config = _config(repo, tmp_path, mode="light")
        # Pre-existing FULL-mode results must survive a light run
        config.results_dir.mkdir(parents=True)
        full_json = config.results_dir / "gerrit-review-120_ps1.json"
        full_json.write_text(json.dumps(REVIEW_SPEC))

        results = run_batch(config, [_change(120, sha)])

        assert results[0].status == STATUS_FINDINGS
        assert results[0].mode == "light"
        assert (config.results_dir /
                "gerrit-review-120_ps1-light.json").is_file()
        assert (config.results_dir /
                "review-metadata-120_ps1-light.json").is_file()
        assert list(
            config.results_dir.glob("kreview-120_ps1-light-*.log"))
        md = (config.results_dir / "markdown" /
              "120_change_120_ps1-light.md")
        assert md.is_file()
        assert full_json.exists()  # untouched by the light run

        summary = json.loads(
            (config.results_dir / "summary.json").read_text())
        assert "120" not in summary
        assert summary["120-light"]["mode"] == "light"
        assert summary["120-light"]["number"] == 120
        assert summary["120-light"]["json"] == \
            "gerrit-review-120_ps1-light.json"

    def test_light_clean_does_not_supersede_full(self, repo, tmp_path,
                                                 stub_claude):
        """A clean light run only supersedes light artifacts — a full
        run's findings JSON for the same change+ps stays."""
        sha = _git(repo, "rev-parse", "HEAD")  # no markers => clean
        config = _config(repo, tmp_path, mode="light")
        config.results_dir.mkdir(parents=True)
        full_json = config.results_dir / "gerrit-review-121_ps1.json"
        full_json.write_text(json.dumps(REVIEW_SPEC))
        light_json = config.results_dir / "gerrit-review-121_ps1-light.json"
        light_json.write_text(json.dumps(REVIEW_SPEC))

        results = run_batch(config, [_change(121, sha)])

        assert results[0].status == STATUS_CLEAN
        assert full_json.exists()        # full results untouched
        assert not light_json.exists()   # stale light result superseded

    def test_per_run_logs_preserved(self, repo, tmp_path, stub_claude):
        """Each run writes its own stamped log; a re-review never
        overwrites the previous run's log."""
        sha = _git(repo, "rev-parse", "HEAD")
        config = _config(repo, tmp_path)
        run_batch(config, [_change(140, sha)])
        first = list(config.results_dir.glob("kreview-140_ps1-*.log"))
        assert len(first) == 1
        import time as time_mod
        time_mod.sleep(1.1)  # stamp granularity is one second
        run_batch(config, [_change(140, sha)])
        logs = sorted(config.results_dir.glob("kreview-140_ps1-*.log"))
        assert len(logs) == 2
        summary = json.loads(
            (config.results_dir / "summary.json").read_text())
        # the manifest names the latest run's log
        assert summary["140"]["log"] == logs[-1].name

    def test_clean_rereview_supersedes_stale_findings(self, repo, tmp_path,
                                                      stub_claude):
        """A clean re-review of the same change+patchset removes the
        earlier findings JSON and replaces the markdown report, so the
        results directory never shows findings the latest run
        withdrew."""
        sha = _git(repo, "rev-parse", "HEAD")
        config = _config(repo, tmp_path)
        config.results_dir.mkdir(parents=True)
        stale_json = config.results_dir / "gerrit-review-105_ps1.json"
        stale_json.write_text(json.dumps(REVIEW_SPEC))
        stale_invalid = config.results_dir / "gerrit-review-105_ps1.invalid"
        stale_invalid.write_text("{oops")
        md_dir = config.results_dir / "markdown"
        md_dir.mkdir()
        stale_md = md_dir / "105_change_105_ps1.md"
        stale_md.write_text("# old findings report\n")

        results = run_batch(config, [_change(105, sha)])

        assert results[0].status == STATUS_CLEAN
        assert not stale_json.exists()
        assert not stale_invalid.exists()
        assert "clean — no findings" in stale_md.read_text()
        summary = json.loads(
            (config.results_dir / "summary.json").read_text())
        assert summary["105"]["json"] is None
        assert summary["105"]["markdown"] == "markdown/105_change_105_ps1.md"

    def test_kill_running_reviews_stops_the_agents(self, repo, tmp_path,
                                                   stub_claude):
        """An interrupted batch kills the running agents — they live
        in their own sessions, so without the explicit group-kill a
        cancelled review keeps running (and billing) headless."""
        import threading
        import time as time_mod
        from lreview.runner import kill_running_reviews
        sha = _commit_with_marker(repo, "SLEEP_MARKER")  # stub sleeps 30s
        config = _config(repo, tmp_path)
        results = []
        worker = threading.Thread(
            target=lambda: results.extend(
                run_batch(config, [_change(150, sha)])))
        start = time_mod.monotonic()
        worker.start()
        killed = 0
        while time_mod.monotonic() - start < 15 and not killed:
            killed = kill_running_reviews(grace=2.0)
            time_mod.sleep(0.1)
        worker.join(timeout=20)
        assert killed == 1
        assert not worker.is_alive()
        # far faster than the stub's 30s sleep, and recorded failed
        assert time_mod.monotonic() - start < 25
        assert results[0].status == STATUS_FAILED

    def test_no_metadata_means_incomplete_not_clean(self, repo, tmp_path,
                                                    stub_claude):
        sha = _commit_with_marker(repo, "NO_METADATA_MARKER")
        config = _config(repo, tmp_path)
        results = run_batch(config, [_change(111, sha)])
        assert results[0].status == STATUS_FAILED
        assert "did not run to completion" in results[0].error

    def test_github_findings_reach_the_reports(self, repo, tmp_path,
                                               stub_claude):
        from lreview.text import batch_text
        pr = _github_pr(repo, {"src.c": "int a;\nint b;\n",
                               "RESULT_MARKER": json.dumps(GITHUB_RESULT)})
        config = _config(repo, tmp_path)
        result, = run_batch(config, [pr])
        assert result.status == STATUS_FINDINGS
        assert result.findings == 2
        md = result.markdown_path.read_text()
        assert "2 finding(s)" in md
        assert "### 1. `src.c` (line 2)" in md
        assert "### 2. general" in md
        text = batch_text([result])
        assert "Findings (2)" in text
        assert "(1) src.c (line 2)" in text
        assert "(2) general" in text

    @pytest.mark.parametrize("markers", [
        {},  # review-metadata.json only
        {"HAS_FINDINGS": json.dumps(REVIEW_SPEC)},  # gerrit-review.json
    ], ids=["metadata-only", "gerrit-review-json"])
    def test_github_without_review_result_is_not_clean(
            self, repo, tmp_path, stub_claude, markers):
        """review-result.json is the GitHub contract for every completed
        review, clean or not; without it the run did not deliver."""
        pr = _github_pr(repo, {"src.c": "int a;\n", **markers})
        config = _config(repo, tmp_path)
        config.results_dir.mkdir(parents=True)
        earlier = config.results_dir / f"review-result-{pr.slug}.json"
        earlier.write_text(json.dumps(GITHUB_RESULT))
        result, = run_batch(config, [pr])
        assert result.status == STATUS_FAILED
        assert "no review-result.json" in result.error
        if markers:
            assert "gerrit-review.json instead" in result.error
        assert earlier.is_file()  # not superseded by a failed run

    def test_github_invalid_result_is_never_postable(self, repo, tmp_path,
                                                     stub_claude):
        """Output that fails validation must not land under the name a
        manifest entry of an earlier run of the same head points at."""
        invalid = {"version": 1, "message": "m", "findings": [
            {"path": "base.txt", "line": 1, "message": "not added"}]}
        pr = _github_pr(repo, {"src.c": "int a;\n",
                               "RESULT_MARKER": json.dumps(invalid)})
        config = _config(repo, tmp_path)
        config.results_dir.mkdir(parents=True)
        earlier = config.results_dir / f"review-result-{pr.slug}.json"
        earlier.write_text(json.dumps(GITHUB_RESULT))
        result, = run_batch(config, [pr])
        assert result.status == STATUS_INVALID_JSON
        assert "base.txt:1 is not an added PR line" in result.error
        assert json.loads(earlier.read_text()) == GITHUB_RESULT
        kept = earlier.with_suffix(".invalid")
        assert json.loads(kept.read_text()) == invalid

    def test_top_level_array_is_invalid_not_crash(self, repo, tmp_path,
                                                  stub_claude):
        sha = _commit_with_marker(repo, "ARRAY_MARKER")
        config = _config(repo, tmp_path)
        results = run_batch(config, [_change(112, sha)])
        assert results[0].status == STATUS_INVALID_JSON
        assert "JSON object" in results[0].error
        # summary is still written
        assert (config.results_dir / "summary.json").is_file()

    def test_worker_crash_recorded_not_propagated(self, repo, tmp_path,
                                                  stub_claude, monkeypatch):
        sha = _git(repo, "rev-parse", "HEAD")
        config = _config(repo, tmp_path)

        def boom(*args, **kwargs):
            raise RuntimeError("worker exploded")

        monkeypatch.setattr("lreview.runner.run_review", boom)
        results = run_batch(config, [_change(113, sha)])
        assert results[0].status == STATUS_FAILED
        assert "worker exploded" in results[0].error
        # summary written, worktree cleaned up despite the crash
        summary = json.loads(
            (config.results_dir / "summary.json").read_text())
        assert summary["113"]["status"] == STATUS_FAILED
        assert not any((tmp_path / "worktrees").glob("kreview_*"))

    def test_timeout(self, repo, tmp_path, stub_claude):
        sha = _commit_with_marker(repo, "SLEEP_MARKER")
        config = _config(repo, tmp_path, timeout=2)
        results = run_batch(config, [_change(201, sha)])
        assert results[0].status == STATUS_TIMEOUT
        assert not any((tmp_path / "worktrees").glob("kreview_*"))

    def test_keep_worktrees(self, repo, tmp_path, stub_claude):
        sha = _git(repo, "rev-parse", "HEAD")
        config = _config(repo, tmp_path, keep_worktrees=True)
        run_batch(config, [_change(301, sha)])
        kept = list((tmp_path / "worktrees").glob("kreview_301_ps1.*"))
        assert len(kept) == 1 and kept[0].is_dir()

    def test_missing_sha_fails_gracefully(self, repo, tmp_path, stub_claude):
        config = _config(repo, tmp_path)
        results = run_batch(config, [_change(401, "f" * 40)])
        assert results[0].status == STATUS_FAILED
        assert "worktree" in results[0].error or "fetch" in results[0].error

    def test_stale_registration_is_pruned(self, repo, tmp_path, stub_claude):
        """A registered worktree whose dir was deleted out-of-band must
        not block future reviews of the same change."""
        import shutil
        # The exact path prepare_worktree will use for this change
        dest = tmp_path / "worktrees" / f"kreview_501_ps1.{os.getpid()}"
        subprocess.run(
            ["git", "-C", str(repo), "worktree", "add", "--detach",
             str(dest), "HEAD"], capture_output=True, check=True)
        shutil.rmtree(dest)

        sha = _git(repo, "rev-parse", "HEAD")
        config = _config(repo, tmp_path)
        results = run_batch(config, [_change(501, sha)])
        assert results[0].status == STATUS_CLEAN

    def test_local_refs_in_worktrees(self, repo, tmp_path, stub_claude):
        from lreview.gerrit import LocalChange
        sha = _commit_with_marker(
            repo, "HAS_FINDINGS", json.dumps(REVIEW_SPEC))
        _git(repo, "branch", "feat/my-branch", sha)
        change = LocalChange(
            ref_name="feat/my-branch", sha=sha, subject="local subject")
        config = _config(repo, tmp_path)
        results = run_batch(config, [change])

        assert results[0].status == STATUS_FINDINGS
        slug = f"feat_my-branch_{sha[:7]}"
        assert results[0].change.slug == slug
        assert (config.results_dir / f"gerrit-review-{slug}.json").is_file()
        summary = json.loads(
            (config.results_dir / "summary.json").read_text())
        assert summary[slug]["local"] is True
        assert summary[slug]["ref_name"] == "feat/my-branch"
        assert summary[slug]["number"] is None
        # Markdown report named by ref+sha (no Gerrit number/ps)
        md = (config.results_dir / "markdown" /
              f"{slug}_local_subject.md")
        assert md.is_file()
        assert md.read_text().startswith(
            "# feat/my-branch — local subject")
        assert summary[slug]["markdown"] == f"markdown/{md.name}"
        # worktree cleaned up; repo untouched
        assert not any((tmp_path / "worktrees").glob("kreview_*"))
        assert not (repo / "gerrit-review.json").exists()

    def test_local_in_place(self, repo, tmp_path, stub_claude):
        from lreview.gerrit import LocalChange
        sha = _commit_with_marker(
            repo, "HAS_FINDINGS", json.dumps(REVIEW_SPEC))
        _git(repo, "checkout", "-q", sha)
        # a stale artifact from an old manual run must not be collected
        (repo / "gerrit-review.json").write_text('{"message": "STALE"}')

        change = LocalChange(ref_name="HEAD", sha=sha, subject="s")
        config = _config(repo, tmp_path)
        results = run_batch(config, [change], in_place=True)

        assert results[0].status == STATUS_FINDINGS
        collected = json.loads(
            (config.results_dir /
             f"gerrit-review-{change.slug}.json").read_text())
        assert collected == REVIEW_SPEC  # fresh, not the stale file
        stale = list(config.results_dir.glob("stale-*gerrit-review.json"))
        assert len(stale) == 1
        assert "STALE" in stale[0].read_text()
        # no worktrees were made; repo artifacts cleaned afterwards
        assert not (tmp_path / "worktrees").exists()
        assert not (repo / "gerrit-review.json").exists()
        assert not (repo / "review-metadata.json").exists()
        # Markdown report for the in-place local review
        md = (config.results_dir / "markdown" /
              f"HEAD_{sha[:7]}_s.md")
        assert md.is_file()
        assert "local review — not tied to a Gerrit change" in md.read_text()

    def test_memory_prompt_and_update_tracking(self, repo, tmp_path,
                                               stub_claude):
        """With memory_db set: the prompt names the memory doc, and
        an unchanged doc is flagged as not updated."""
        from lreview.runner import review_prompt
        sha = _git(repo, "rev-parse", "HEAD")
        change = _change(701, sha)
        config = _config(repo, tmp_path, memory_db=tmp_path / "db")

        prompt = review_prompt(config, change)
        assert "memory-prompt.md" in prompt
        doc = tmp_path / "db" / "701-change_701.md"
        assert str(doc) in prompt
        assert doc.is_file()  # skeleton pre-created

        # The stub claude never touches the doc -> not updated
        results = run_batch(config, [change])
        assert results[0].memory_path == doc
        assert results[0].memory_updated is False
        # ...but the completed run still counts as an iteration,
        # bumped by the runner (never by the agent)
        assert results[0].memory_reviews == 1
        assert "reviews: 1" in doc.read_text()
        summary = json.loads(
            (config.results_dir / "summary.json").read_text())
        assert summary["701"]["memory"] == str(doc)
        assert summary["701"]["memory_reviews"] == 1

        # a second completed run makes it iteration 2
        results = run_batch(config, [change])
        assert results[0].memory_reviews == 2
        assert "reviews: 2" in doc.read_text()

    def test_memory_updated_detected(self, repo, tmp_path, stub_claude,
                                     monkeypatch):
        """A review that rewrites its memory doc is detected. The stub
        writes the doc when MEMDOC_FILE names it."""
        import stat as stat_mod
        sha = _git(repo, "rev-parse", "HEAD")
        change = _change(702, sha)
        db = tmp_path / "db"
        doc = db / "702-change_702.md"

        # extend the stub: also write the memory doc
        stub = tmp_path / "bin" / "claude"
        stub.write_text(STUB_CLAUDE.replace(
            'echo \'{"type":"system","subtype":"estimated_tokens"',
            'if [ -n "$MEMDOC_FILE" ]; then echo notes > "$MEMDOC_FILE"; fi\n'
            'echo \'{"type":"system","subtype":"estimated_tokens"'))
        stub.chmod(stub.stat().st_mode | stat_mod.S_IEXEC)
        monkeypatch.setenv("MEMDOC_FILE", str(doc))

        config = _config(repo, tmp_path, memory_db=db)
        results = run_batch(config, [change])
        assert results[0].memory_path == doc
        assert results[0].memory_updated is True
        # the stub wrote a bare doc; the runner restored a minimal
        # frontmatter for the iteration counter and the session around it
        text = doc.read_text()
        assert "notes" in text
        assert text.startswith("---\nreviews: 1\nclaude-session-full: sess-1 ")

    def test_no_memory_without_flag(self, repo, tmp_path, stub_claude):
        from lreview.runner import review_prompt
        sha = _git(repo, "rev-parse", "HEAD")
        change = _change(703, sha)
        config = _config(repo, tmp_path)  # memory_db not set

        assert "memory" not in review_prompt(config, change)
        results = run_batch(config, [change])
        assert results[0].memory_path is None
        assert not (tmp_path / "db").exists()

    def test_summary_merges_previous_runs(self, repo, tmp_path, stub_claude):
        sha = _git(repo, "rev-parse", "HEAD")
        config = _config(repo, tmp_path)
        run_batch(config, [_change(601, sha)])
        run_batch(config, [_change(602, sha)])
        summary = json.loads(
            (config.results_dir / "summary.json").read_text())
        assert set(summary) == {"601", "602"}


class TestUpdateSummary:

    def _result(self, number, sha, status=STATUS_FINDINGS, ps=2):
        from lreview.runner import ReviewResult
        change = ResolvedChange(
            number=number, project="p", subject="s", sha=sha,
            patchset=ps, ref="r", base_url="https://gerrit.invalid")
        return ReviewResult(change, status, findings=1)

    def test_posted_survives_same_sha_rereview(self, tmp_path):
        update_summary(tmp_path, [self._result(700, "a" * 40)])
        summary = json.loads((tmp_path / "summary.json").read_text())
        summary["700"]["posted"] = True
        summary["700"]["posted_at"] = "2026-01-01T00:00:00+00:00"
        (tmp_path / "summary.json").write_text(json.dumps(summary))

        update_summary(tmp_path, [self._result(700, "a" * 40)])
        summary = json.loads((tmp_path / "summary.json").read_text())
        assert summary["700"]["posted"] is True
        assert summary["700"]["posted_at"] == "2026-01-01T00:00:00+00:00"

    def test_new_patchset_resets_posted_keeps_history(self, tmp_path):
        update_summary(tmp_path, [self._result(701, "a" * 40, ps=2)])
        summary = json.loads((tmp_path / "summary.json").read_text())
        summary["701"]["posted"] = True
        summary["701"]["posted_at"] = "2026-01-01T00:00:00+00:00"
        (tmp_path / "summary.json").write_text(json.dumps(summary))

        update_summary(tmp_path, [self._result(701, "b" * 40, ps=3)])
        summary = json.loads((tmp_path / "summary.json").read_text())
        assert summary["701"]["posted"] is False
        assert summary["701"]["last_posted"]["sha"] == "a" * 40
        assert summary["701"]["last_posted"]["patchset"] == 2

    def test_failed_rereview_keeps_posted_history(self, tmp_path):
        update_summary(tmp_path, [self._result(702, "a" * 40, ps=2)])
        summary = json.loads((tmp_path / "summary.json").read_text())
        summary["702"]["posted"] = True
        (tmp_path / "summary.json").write_text(json.dumps(summary))

        update_summary(
            tmp_path,
            [self._result(702, "b" * 40, status=STATUS_FAILED, ps=3)])
        summary = json.loads((tmp_path / "summary.json").read_text())
        assert summary["702"]["status"] == STATUS_FAILED
        assert summary["702"]["last_posted"]["sha"] == "a" * 40

    def test_corrupt_summary_backed_up_not_wiped(self, tmp_path, capsys):
        (tmp_path / "summary.json").write_text("{truncated")
        update_summary(tmp_path, [self._result(703, "a" * 40)])
        summary = json.loads((tmp_path / "summary.json").read_text())
        assert "703" in summary
        backups = list(tmp_path.glob("summary.json.corrupt-*"))
        assert len(backups) == 1
        assert backups[0].read_text() == "{truncated"


class TestRecentCommits:
    """worktree.recent_commits backs 'lreview run --last N'."""

    def _repo(self, tmp_path, count):
        import subprocess
        env = {"GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@e",
               "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@e",
               "PATH": os.environ["PATH"], "HOME": str(tmp_path)}
        subprocess.run(["git", "init", "-q", str(tmp_path)], check=True,
                       env=env)
        for i in range(count):
            (tmp_path / "f").write_text(str(i))
            subprocess.run(["git", "-C", str(tmp_path), "add", "f"],
                           check=True, env=env)
            subprocess.run(
                ["git", "-C", str(tmp_path), "commit", "-qm", f"c{i}"],
                check=True, env=env)
        return tmp_path

    def test_newest_first(self, tmp_path):
        from lreview.worktree import commit_subject, recent_commits
        repo = self._repo(tmp_path, 4)
        shas = recent_commits(repo, 3)
        assert len(shas) == 3
        assert [commit_subject(repo, s) for s in shas] == ["c3", "c2", "c1"]

    def test_short_history_returns_what_there_is(self, tmp_path):
        from lreview.worktree import recent_commits
        repo = self._repo(tmp_path, 2)
        assert len(recent_commits(repo, 10)) == 2


def test_reap_orphan_worktrees_removes_only_dead_pids(tmp_path):
    """A worktree whose creating pid is gone is stranded; a live one is not."""
    from lreview import worktree as wt

    wtrees = tmp_path / "worktrees"
    wtrees.mkdir()
    dead = wtrees / f"kreview_HEAD_abc1234.{_dead_pid()}"
    live = wtrees / f"kreview_HEAD_def5678.{os.getpid()}"
    other = wtrees / "not-a-review"
    for d in (dead, live, other):
        d.mkdir()
        (d / "file").write_text("x")

    assert wt.reap_orphan_worktrees(wtrees) == 1
    assert not dead.exists()
    assert live.exists()
    assert other.exists()
    # a second pass has nothing left to do
    assert wt.reap_orphan_worktrees(wtrees) == 0


def _dead_pid() -> int:
    """A pid with no live process behind it."""
    pid = os.fork()
    if pid == 0:
        os._exit(0)
    os.waitpid(pid, 0)
    return pid


class TestClaudeSessionRecording:
    """A completed --memory review records its Claude session in the
    memory document, per mode; nothing else records one."""

    def test_parse_session_id(self, tmp_path):
        from lreview.runner import parse_session_id
        log = tmp_path / "x.log"
        log.write_text('{"type":"system","subtype":"init","session_id":"a1"}\n'
                       '{"type":"result","session_id":"a1"}\n')
        assert parse_session_id(log) == "a1"
        log.write_text('noise\n{"type":"result","session_id":"b2"}\n')
        assert parse_session_id(log) == "b2"
        log.write_text("no events at all\n")
        assert parse_session_id(log) is None

    def test_completed_review_records_its_session(self, repo, tmp_path,
                                                  stub_claude, monkeypatch):
        from lreview.memory import read_session
        monkeypatch.setenv("STUB_SESSION", "sess-abc")
        sha = _git(repo, "rev-parse", "HEAD")
        config = _config(repo, tmp_path, memory_db=tmp_path / "db")
        results = run_batch(config, [_change(801, sha)])
        assert results[0].session_id == "sess-abc"
        session = read_session(results[0].memory_path, "full")
        assert session.session_id == "sess-abc"
        assert session.reviewed == f"ps1 {sha[:12]}"

    def test_light_review_records_the_light_session(self, repo, tmp_path,
                                                    stub_claude,
                                                    monkeypatch):
        from lreview.memory import read_session
        monkeypatch.setenv("STUB_SESSION", "sess-light")
        sha = _git(repo, "rev-parse", "HEAD")
        config = _config(repo, tmp_path, mode="light",
                         memory_db=tmp_path / "db")
        results = run_batch(config, [_change(802, sha)])
        assert read_session(results[0].memory_path, "light").session_id \
            == "sess-light"
        assert read_session(results[0].memory_path, "full") is None

    def test_failed_review_records_nothing(self, repo, tmp_path,
                                           stub_claude):
        from lreview.memory import read_session
        sha = _commit_with_marker(repo, "FAIL_MARKER")
        config = _config(repo, tmp_path, memory_db=tmp_path / "db")
        results = run_batch(config, [_change(803, sha)])
        assert results[0].status == STATUS_FAILED
        assert read_session(results[0].memory_path, "full") is None

    def test_no_memory_records_nothing(self, repo, tmp_path, stub_claude):
        sha = _git(repo, "rev-parse", "HEAD")
        config = _config(repo, tmp_path)
        results = run_batch(config, [_change(804, sha)])
        assert results[0].memory_path is None
        assert not (tmp_path / "db").exists()

    def test_other_agents_record_nothing(self, repo, tmp_path, stub_claude):
        from lreview.memory import read_session
        codex = tmp_path / "bin" / "codex"
        codex.write_text(STUB_CLAUDE)
        codex.chmod(codex.stat().st_mode | stat.S_IEXEC)
        sha = _git(repo, "rev-parse", "HEAD")
        config = _config(repo, tmp_path, agent="codex",
                         memory_db=tmp_path / "db")
        results = run_batch(config, [_change(805, sha)])
        assert results[0].status == STATUS_CLEAN
        assert read_session(results[0].memory_path, "full") is None


def _claude_session_file(tmp_path, monkeypatch, session_id):
    """Where Claude Code keeps a session; lreview checks it exists."""
    config_dir = tmp_path / "claude-config"
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(config_dir))
    path = config_dir / "projects" / "-some-worktree" / f"{session_id}.jsonl"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("{}\n")
    return path


def _invocations(args_log: Path) -> list[list[str]]:
    runs, current = [], []
    for line in args_log.read_text().splitlines():
        if line == "--":
            runs.append(current)
            current = []
        else:
            current.append(line)
    return runs


class TestClaudeSessionResume:
    """--memory runs resume the recorded Claude session (forked), with
    a fresh session as the fallback."""

    def test_claude_resume_and_settings_flags(self):
        from lreview.agents import get_agent
        cmd = get_agent("claude").build_cmd(
            "opus", None, [], "PROMPT", resume="sess-1", settings="{}")
        assert cmd[cmd.index("--resume") + 1] == "sess-1"
        assert "--fork-session" in cmd
        assert cmd[cmd.index("--settings") + 1] == "{}"

    def test_other_agents_ignore_them(self):
        from lreview.agents import get_agent
        cmd = get_agent("codex").build_cmd(
            None, None, [], "PROMPT", resume="sess-1", settings="{}")
        assert "--resume" not in cmd and "--settings" not in cmd

    def test_compaction_hook_rereads_the_memory(self, tmp_path):
        from lreview.memory import MEMORY_PROMPT_PATH
        from lreview.runner import compaction_settings
        doc = tmp_path / "db" / "1-x.md"
        settings = json.loads(compaction_settings(doc))
        (entry,) = settings["hooks"]["SessionStart"]
        assert entry["matcher"] == "compact"
        out = subprocess.run(entry["hooks"][0]["command"], shell=True,
                             capture_output=True, text=True).stdout
        assert str(doc) in out and str(MEMORY_PROMPT_PATH) in out

    def test_resume_prompt_says_where_the_code_is_now(self, tmp_path):
        from lreview.memory import ClaudeSession
        from lreview.runner import review_prompt
        config = _config(tmp_path, tmp_path, memory_db=tmp_path / "db")
        prompt = review_prompt(
            config, _change(901, "d" * 40),
            session=ClaudeSession("sess-1", "ps1 aaaaaaaaaaaa"),
            worktree=Path("/wt/new"))
        assert "continues your earlier review" in prompt
        assert "ps1 aaaaaaaaaaaa" in prompt
        assert "/wt/new" in prompt
        assert "review-core.md" in prompt

    def _review_twice(self, repo, tmp_path, monkeypatch, **config_kwargs):
        args_log = tmp_path / "args.log"
        monkeypatch.setenv("STUB_ARGS_LOG", str(args_log))
        sha = _git(repo, "rev-parse", "HEAD")
        change = _change(902, sha)
        config = _config(repo, tmp_path, memory_db=tmp_path / "db",
                         **config_kwargs)
        monkeypatch.setenv("STUB_SESSION", "sess-1")
        first = run_batch(config, [change])[0]
        monkeypatch.setenv("STUB_SESSION", "sess-2")
        second = run_batch(config, [change])[0]
        return first, second, _invocations(args_log)

    def test_second_run_resumes_a_fork(self, repo, tmp_path, stub_claude,
                                       monkeypatch):
        from lreview.memory import read_session
        _claude_session_file(tmp_path, monkeypatch, "sess-1")
        first, second, runs = self._review_twice(repo, tmp_path,
                                                 monkeypatch)
        assert "--resume" not in runs[0]
        assert runs[1][runs[1].index("--resume") + 1] == "sess-1"
        assert "--fork-session" in runs[1]
        assert "--settings" in runs[0] and "--settings" in runs[1]
        assert second.status == STATUS_CLEAN
        assert read_session(second.memory_path, "full").session_id \
            == "sess-2"

    def test_no_resume_starts_fresh(self, repo, tmp_path, stub_claude,
                                    monkeypatch):
        from lreview.memory import read_session
        _claude_session_file(tmp_path, monkeypatch, "sess-1")
        _, second, runs = self._review_twice(repo, tmp_path, monkeypatch,
                                             resume=False)
        assert "--resume" not in runs[1]
        assert read_session(second.memory_path, "full").session_id \
            == "sess-2"

    def test_a_session_claude_no_longer_has_is_not_resumed(
            self, repo, tmp_path, stub_claude, monkeypatch):
        from lreview.memory import read_session
        monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(tmp_path / "empty"))
        _, second, runs = self._review_twice(repo, tmp_path, monkeypatch)
        assert "--resume" not in runs[1]
        assert second.status == STATUS_CLEAN
        assert read_session(second.memory_path, "full").session_id \
            == "sess-2"

    def test_a_failed_resume_retries_fresh(self, repo, tmp_path,
                                           stub_claude, monkeypatch):
        from lreview.memory import read_session
        _claude_session_file(tmp_path, monkeypatch, "sess-1")
        monkeypatch.setenv("STUB_NO_SESSION", "1")
        _, second, runs = self._review_twice(repo, tmp_path, monkeypatch)
        assert "--resume" in runs[1] and "--resume" not in runs[2]
        assert second.status == STATUS_CLEAN
        assert read_session(second.memory_path, "full").session_id \
            == "sess-2"

    def test_without_memory_nothing_is_resumed(self, repo, tmp_path,
                                               stub_claude, monkeypatch):
        args_log = tmp_path / "args.log"
        monkeypatch.setenv("STUB_ARGS_LOG", str(args_log))
        sha = _git(repo, "rev-parse", "HEAD")
        run_batch(_config(repo, tmp_path), [_change(903, sha)])
        (run,) = _invocations(args_log)
        assert "--resume" not in run and "--settings" not in run


class TestPreload:

    def _prompts(self, tmp_path):
        from lreview.runner import PRELOAD_FILES
        prompts = tmp_path / "prompts"
        for name in PRELOAD_FILES:
            (prompts / name).parent.mkdir(parents=True, exist_ok=True)
            (prompts / name).write_text(f"contents of {name}\n")
        return prompts

    def test_prompt_carries_the_commit(self, repo, tmp_path):
        from lreview.runner import review_prompt
        sha = _commit_with_marker(repo, "NEW_FILE", "hello\n")
        _git(repo, "checkout", "-q", sha)
        config = _config(repo, tmp_path, prompts_dir=self._prompts(tmp_path),
                         preload=True)
        prompt = review_prompt(config, _change(1, sha), worktree=repo)
        assert "Lustre Patch Analysis Protocol in your system prompt" in prompt
        assert "review-core.md" not in prompt
        assert f"commit {sha}" in prompt and "+hello" in prompt

    def test_cmd_names_one_shared_system_file(self, tmp_path):
        config = _config(tmp_path, tmp_path,
                         prompts_dir=self._prompts(tmp_path), preload=True)
        config.results_dir.mkdir(parents=True)
        first = build_agent_cmd(config, _change(1, "a" * 40))
        second = build_agent_cmd(config, _change(2, "b" * 40))
        path = first[first.index("--append-system-prompt-file") + 1]
        assert path == second[second.index("--append-system-prompt-file") + 1]
        text = Path(path).read_text()
        assert text.index("contents of review-core.md") < text.index(
            "contents of subsystem/subsystem.md") < text.index(CLOSING_NOTE)
        assert str(config.prompts_dir) in text
        assert CLOSING_NOTE not in first[2]

    def test_light_mode_is_not_preloaded(self, tmp_path):
        config = _config(tmp_path, tmp_path,
                         prompts_dir=self._prompts(tmp_path), preload=True,
                         mode="light")
        cmd = build_agent_cmd(config, _change(1, "a" * 40))
        assert "--append-system-prompt-file" not in cmd

    def test_large_commit_left_out(self, repo, tmp_path, monkeypatch):
        from lreview import runner
        monkeypatch.setattr(runner, "PRELOAD_COMMIT_LIMIT", 10)
        assert "too large" in runner.commit_text(repo)


def test_run_batch_records_telemetry(repo, tmp_path, stub_claude):
    sha = _commit_with_marker(repo, "HAS_FINDINGS", json.dumps(REVIEW_SPEC))
    config = _config(repo, tmp_path, lean=True)
    result, = run_batch(config, [_change(130, sha)])
    saved = list(config.results_dir.glob("kreview-130_ps1-*.telemetry.json"))
    assert len(saved) == 1
    data = json.loads(saved[0].read_text())
    assert data["run"]["lean"] is True
    assert data["run"]["status"] == STATUS_FINDINGS
    summary = json.loads((config.results_dir / "summary.json").read_text())
    assert summary["130"]["telemetry"] == result.telemetry
    assert "split_usd" in result.telemetry


def test_codex_preload_goes_on_stdin(repo, tmp_path, monkeypatch):
    from lreview.runner import PRELOAD_FILES, run_review
    prompts = tmp_path / "prompts"
    for name in PRELOAD_FILES:
        (prompts / name).parent.mkdir(parents=True, exist_ok=True)
        (prompts / name).write_text(f"contents of {name}\n")
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    stub = bin_dir / "codex"
    # Echo stdin back into the log so the test can see what codex got
    stub.write_text("#!/bin/sh\ncat\n")
    stub.chmod(0o755)
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{os.environ['PATH']}")
    sha = _commit_with_marker(repo, "NEW", "hello\n")
    _git(repo, "checkout", "-q", sha)
    config = _config(repo, tmp_path, prompts_dir=prompts, preload=True,
                     agent="codex", lean=True)
    config.results_dir.mkdir(parents=True)
    result = run_review(config, _change(1, sha), repo)
    seen = result.log_path.read_text()
    assert seen.startswith("# Lustre review protocol")
    assert seen.index("contents of review-core.md") < seen.index("+hello")
    assert result.log_path.with_suffix(".prompt.md").is_file()
