"""Offline end-to-end tests for the batch runner.

A stub `claude` executable is placed on PATH; its behavior is driven by
marker files committed in the test repository, so the whole pipeline
(worktree creation, parallel execution, collection, summary manifest,
worktree cleanup) runs for real without network or a real Claude.
"""

import json
import os
import stat
import subprocess
from pathlib import Path

import pytest

from lreview.gerrit import ResolvedChange, change_ref
from lreview.runner import (
    BatchConfig,
    STATUS_CLEAN,
    STATUS_FAILED,
    STATUS_FINDINGS,
    STATUS_INVALID_JSON,
    STATUS_TIMEOUT,
    build_agent_cmd,
    count_findings,
    run_batch,
    update_summary,
)

REVIEW_SPEC = {
    "tag": "autogenerated:ai-review",
    "message": "Some concerns.",
    "comments": {
        "a.c": [{"line": 1, "message": "x", "unresolved": True}],
        "b.c": [{"line": 2, "message": "y", "unresolved": True},
                {"line": 3, "message": "z", "unresolved": True}],
    },
}

# Behavior is driven by marker files in the worktree (cwd). A completed
# analysis always writes review-metadata.json (as review-core.md
# mandates); NO_METADATA simulates a claude run that bailed out early.
STUB_CLAUDE = """#!/bin/bash
if [ -f FAIL_MARKER ]; then echo "boom"; exit 3; fi
if [ -f SLEEP_MARKER ]; then sleep 30; exit 0; fi
if [ -f NO_METADATA_MARKER ]; then echo "bailed early"; exit 0; fi
SEV=none
if [ -f HAS_FINDINGS ]; then SEV=high; fi
printf '{"author":"a","sha":"s","subject":"t","issues-found":0,\
"issue-severity-score":"%s","issue-severity-explanation":"e"}' "$SEV" \
    > review-metadata.json
if [ -f INVALID_MARKER ]; then printf '{oops' > gerrit-review.json; exit 0; fi
if [ -f ARRAY_MARKER ]; then printf '[]' > gerrit-review.json; exit 0; fi
if [ -f HAS_FINDINGS ]; then cp HAS_FINDINGS gerrit-review.json; fi
echo '{"type":"system","subtype":"estimated_tokens","estimated_tokens":123456}'
echo "Assisted-by: ClaudeCode:claude-fable-5"
echo '{"type":"result","result":"done","total_cost_usd":1.23,"usage":{"input_tokens":10,"cache_creation_input_tokens":1000,"cache_read_input_tokens":50000,"output_tokens":2000}}'
"""


def _git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args], capture_output=True, text=True)
    assert result.returncode == 0, result.stderr
    return result.stdout.strip()


@pytest.fixture
def stub_claude(tmp_path, monkeypatch):
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    stub = bin_dir / "claude"
    stub.write_text(STUB_CLAUDE)
    stub.chmod(stub.stat().st_mode | stat.S_IEXEC)
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{os.environ['PATH']}")
    return stub


@pytest.fixture
def repo(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-q")
    _git(repo, "config", "user.email", "t@example.com")
    _git(repo, "config", "user.name", "Test")
    (repo / "base.txt").write_text("base\n")
    _git(repo, "add", ".")
    _git(repo, "commit", "-q", "-m", "base")
    return repo


def _commit_with_marker(repo: Path, name: str, content: str = "") -> str:
    """Create a commit adding a marker file; return its SHA."""
    _git(repo, "checkout", "-q", "--detach", "HEAD")
    marker = repo / name
    marker.write_text(content)
    _git(repo, "add", name)
    _git(repo, "commit", "-q", "-m", f"add {name}")
    sha = _git(repo, "rev-parse", "HEAD")
    _git(repo, "rm", "-q", name)
    _git(repo, "commit", "-q", "-m", f"remove {name}")
    return sha


def _change(number: int, sha: str) -> ResolvedChange:
    return ResolvedChange(
        number=number, project="test/repo", subject=f"change {number}",
        sha=sha, patchset=1, ref=change_ref(number, 1),
        base_url="https://gerrit.invalid")


def _config(repo: Path, tmp_path: Path, **kwargs) -> BatchConfig:
    return BatchConfig(
        repo=repo,
        results_dir=tmp_path / "results",
        worktrees_dir=tmp_path / "worktrees",
        **kwargs,
    )


class TestBuildAgentCmd:

    def test_default(self, tmp_path):
        config = _config(tmp_path, tmp_path,
                         prompts_dir=Path("/p/kernel"))
        cmd = build_agent_cmd(config)
        assert cmd[:2] == ["claude", "-p"]
        assert cmd[2] == ("Using the prompt /p/kernel/review-core.md "
                          "run a deep dive regression analysis of the "
                          "top commit")
        assert cmd[3:] == ["--dangerously-skip-permissions",
                           "--verbose", "--output-format", "stream-json"]

    def test_model_and_extra_args(self, tmp_path):
        config = _config(tmp_path, tmp_path, model="opus",
                         agent_args=["--max-turns", "50"])
        cmd = build_agent_cmd(config)
        assert cmd[-4:] == ["--model", "opus", "--max-turns", "50"]

    def test_jobs_must_be_positive(self, tmp_path):
        with pytest.raises(ValueError):
            _config(tmp_path, tmp_path, jobs=0)


class TestModelDetection:

    def test_configured_model_wins(self, tmp_path):
        from lreview.runner import detect_model
        log = tmp_path / "x.log"
        log.write_text("Assisted-by: ClaudeCode:claude-opus-4-8\n")
        assert detect_model(log, configured="fable") == "fable"
        assert detect_model(log, configured="claude-sonnet-5") == "sonnet"

    def test_parsed_from_assisted_by_line(self, tmp_path):
        from lreview.runner import detect_model
        log = tmp_path / "x.log"
        log.write_text(
            "review text\nAssisted-by: ClaudeCode:claude-opus-4-8\ndone\n")
        assert detect_model(log) == "opus"

    def test_parsed_from_stream_json_init_event(self, tmp_path):
        from lreview.runner import detect_model
        log = tmp_path / "x.log"
        log.write_text(
            '{"type":"system","subtype":"init","cwd":"/x",'
            '"model":"claude-fable-5","tools":[]}\n'
            '{"type":"result","result":"all good"}\n')
        assert detect_model(log) == "fable"

    def test_unknown_model_uses_tail(self, tmp_path):
        from lreview.runner import detect_model
        log = tmp_path / "x.log"
        log.write_text("Assisted-by: SomeAgent:custom-model-x\n")
        assert detect_model(log) == "custom-model-x"

    def test_no_log_no_model(self, tmp_path):
        from lreview.runner import detect_model
        assert detect_model(None) is None
        assert detect_model(tmp_path / "missing.log") is None
        log = tmp_path / "empty.log"
        log.write_text("no marker here\n")
        assert detect_model(log) is None


class TestProgressTracker:

    def test_status_line(self, tmp_path):
        from lreview.runner import ProgressTracker
        log = tmp_path / "kreview-64086_ps40.log"
        log.write_text("x" * 2048)

        tracker = ProgressTracker(total=3)
        assert tracker.status_line() is None  # nothing running yet

        tracker.start("64086_ps40", log)
        tracker.start("64087_ps12", tmp_path / "missing.log")
        line = tracker.status_line()
        assert "64086_ps40 0m00s 2KB" in line
        assert "64087_ps12 0m00s" in line
        assert "done 0/3" in line

        tracker.finish("64086_ps40")
        line = tracker.status_line()
        assert "64086_ps40" not in line
        assert "done 1/3" in line

        tracker.finish("64087_ps12")
        assert tracker.status_line() is None

    def test_status_line_shows_live_tokens(self, tmp_path):
        from lreview.runner import ProgressTracker
        log = tmp_path / "kreview-64086_ps40.log"
        log.write_text(
            '{"type":"system","subtype":"estimated_tokens",'
            '"estimated_tokens":1000}\n'
            '{"type":"system","subtype":"estimated_tokens",'
            '"estimated_tokens":842000}\n')
        tracker = ProgressTracker(total=1)
        tracker.start("64086_ps40", log)
        assert "64086_ps40 0m00s 842k tok" in tracker.status_line()


class TestTokenParsing:

    def test_format_tokens(self):
        from lreview.runner import format_tokens
        assert format_tokens(None) is None
        assert format_tokens(999) == "999"
        assert format_tokens(53010) == "53k"
        assert format_tokens(2_140_000) == "2.1M"

    def test_live_token_count_latest_wins(self, tmp_path):
        from lreview.runner import live_token_count
        log = tmp_path / "x.log"
        log.write_text(
            '{"type":"system","subtype":"estimated_tokens",'
            '"estimated_tokens":1000,"estimated_tokens_delta":10}\n'
            '{"type":"assistant","message":{}}\n'
            '{"type":"system","subtype":"estimated_tokens",'
            '"estimated_tokens":84200,"estimated_tokens_delta":20}\n')
        assert live_token_count(log) == 84200
        assert live_token_count(tmp_path / "missing.log") is None

    def test_parse_final_usage(self, tmp_path):
        from lreview.runner import parse_final_usage
        log = tmp_path / "x.log"
        log.write_text(
            '{"type":"system","subtype":"init"}\n'
            '{"type":"result","total_cost_usd":4.2,"usage":'
            '{"input_tokens":5,"cache_creation_input_tokens":100,'
            '"cache_read_input_tokens":900,"output_tokens":45}}\n')
        tokens, cost = parse_final_usage(log)
        assert tokens == 1050
        assert cost == 4.2

    def test_parse_final_usage_absent(self, tmp_path):
        from lreview.runner import parse_final_usage
        log = tmp_path / "x.log"
        log.write_text("plain text log with no result event\n")
        assert parse_final_usage(log) == (None, None)
        assert parse_final_usage(tmp_path / "missing.log") == (None, None)


class TestCountFindings:

    def test_dict_format(self):
        assert count_findings(REVIEW_SPEC) == 3

    def test_flat_list(self):
        assert count_findings({"comments": [{"path": "a", "line": 1,
                                             "message": "m"}]}) == 1

    def test_empty(self):
        assert count_findings({}) == 0


class TestRunBatch:

    def test_findings_clean_failed_invalid(self, repo, tmp_path, stub_claude):
        sha_findings = _commit_with_marker(
            repo, "HAS_FINDINGS", json.dumps(REVIEW_SPEC))
        sha_clean = _git(repo, "rev-parse", "HEAD")
        sha_failed = _commit_with_marker(repo, "FAIL_MARKER")
        sha_invalid = _commit_with_marker(repo, "INVALID_MARKER")

        changes = [
            _change(101, sha_findings),
            _change(102, sha_clean),
            _change(103, sha_failed),
            _change(104, sha_invalid),
        ]
        config = _config(repo, tmp_path, jobs=4)
        results = {r.change.number: r for r in run_batch(config, changes)}

        assert results[101].status == STATUS_FINDINGS
        assert results[101].findings == 3
        assert results[101].severity == "high"
        assert results[101].model == "fable"  # parsed from Assisted-by
        assert results[101].tokens == 53010   # from the result event
        assert results[101].cost_usd == 1.23
        assert results[102].status == STATUS_CLEAN
        assert results[102].severity == "none"
        assert results[103].status == STATUS_FAILED
        assert results[104].status == STATUS_INVALID_JSON

        # Collected artifacts are per-change suffixed and valid
        collected = config.results_dir / "gerrit-review-101_ps1.json"
        assert json.loads(collected.read_text()) == REVIEW_SPEC
        # Human-readable markdown report generated for findings
        md = config.results_dir / "markdown" / "101_change_101_ps1.md"
        assert md.is_file()
        assert "## Findings" in md.read_text()
        assert results[101].markdown_path == md
        metadata = config.results_dir / "review-metadata-101_ps1.json"
        assert json.loads(
            metadata.read_text())["issue-severity-score"] == "high"
        # Invalid output is preserved for debugging
        assert (config.results_dir / "gerrit-review-104_ps1.invalid").exists()
        # Logs exist per change
        assert (config.results_dir / "kreview-103_ps1.log").exists()

        # Worktrees were cleaned up
        assert not any((tmp_path / "worktrees").glob("kreview_*"))

        # Summary manifest records everything
        summary = json.loads(
            (config.results_dir / "summary.json").read_text())
        assert summary["101"]["status"] == STATUS_FINDINGS
        assert summary["101"]["findings"] == 3
        assert summary["101"]["severity"] == "high"
        assert summary["101"]["model"] == "fable"
        assert summary["101"]["tokens"] == 53010
        assert summary["101"]["cost_usd"] == 1.23
        assert summary["101"]["markdown"] == "markdown/101_change_101_ps1.md"
        assert summary["101"]["sha"] == sha_findings
        assert summary["101"]["posted"] is False
        assert summary["102"]["status"] == STATUS_CLEAN
        assert summary["103"]["error"] == "claude exited 3"

    def test_no_metadata_means_incomplete_not_clean(self, repo, tmp_path,
                                                    stub_claude):
        sha = _commit_with_marker(repo, "NO_METADATA_MARKER")
        config = _config(repo, tmp_path)
        results = run_batch(config, [_change(111, sha)])
        assert results[0].status == STATUS_FAILED
        assert "did not run to completion" in results[0].error

    def test_top_level_array_is_invalid_not_crash(self, repo, tmp_path,
                                                  stub_claude):
        sha = _commit_with_marker(repo, "ARRAY_MARKER")
        config = _config(repo, tmp_path)
        results = run_batch(config, [_change(112, sha)])
        assert results[0].status == STATUS_INVALID_JSON
        assert "JSON object" in results[0].error
        # summary is still written
        assert (config.results_dir / "summary.json").is_file()

    def test_worker_crash_recorded_not_propagated(self, repo, tmp_path,
                                                  stub_claude, monkeypatch):
        sha = _git(repo, "rev-parse", "HEAD")
        config = _config(repo, tmp_path)

        def boom(*args, **kwargs):
            raise RuntimeError("worker exploded")

        monkeypatch.setattr("lreview.runner.run_review", boom)
        results = run_batch(config, [_change(113, sha)])
        assert results[0].status == STATUS_FAILED
        assert "worker exploded" in results[0].error
        # summary written, worktree cleaned up despite the crash
        summary = json.loads(
            (config.results_dir / "summary.json").read_text())
        assert summary["113"]["status"] == STATUS_FAILED
        assert not any((tmp_path / "worktrees").glob("kreview_*"))

    def test_timeout(self, repo, tmp_path, stub_claude):
        sha = _commit_with_marker(repo, "SLEEP_MARKER")
        config = _config(repo, tmp_path, timeout=2)
        results = run_batch(config, [_change(201, sha)])
        assert results[0].status == STATUS_TIMEOUT
        assert not any((tmp_path / "worktrees").glob("kreview_*"))

    def test_keep_worktrees(self, repo, tmp_path, stub_claude):
        sha = _git(repo, "rev-parse", "HEAD")
        config = _config(repo, tmp_path, keep_worktrees=True)
        run_batch(config, [_change(301, sha)])
        kept = list((tmp_path / "worktrees").glob("kreview_301_ps1.*"))
        assert len(kept) == 1 and kept[0].is_dir()

    def test_missing_sha_fails_gracefully(self, repo, tmp_path, stub_claude):
        config = _config(repo, tmp_path)
        results = run_batch(config, [_change(401, "f" * 40)])
        assert results[0].status == STATUS_FAILED
        assert "worktree" in results[0].error or "fetch" in results[0].error

    def test_stale_registration_is_pruned(self, repo, tmp_path, stub_claude):
        """A registered worktree whose dir was deleted out-of-band must
        not block future reviews of the same change."""
        import shutil
        # The exact path prepare_worktree will use for this change
        dest = tmp_path / "worktrees" / f"kreview_501_ps1.{os.getpid()}"
        subprocess.run(
            ["git", "-C", str(repo), "worktree", "add", "--detach",
             str(dest), "HEAD"], capture_output=True, check=True)
        shutil.rmtree(dest)

        sha = _git(repo, "rev-parse", "HEAD")
        config = _config(repo, tmp_path)
        results = run_batch(config, [_change(501, sha)])
        assert results[0].status == STATUS_CLEAN

    def test_local_refs_in_worktrees(self, repo, tmp_path, stub_claude):
        from lreview.gerrit import LocalChange
        sha = _commit_with_marker(
            repo, "HAS_FINDINGS", json.dumps(REVIEW_SPEC))
        _git(repo, "branch", "feat/my-branch", sha)
        change = LocalChange(
            ref_name="feat/my-branch", sha=sha, subject="local subject")
        config = _config(repo, tmp_path)
        results = run_batch(config, [change])

        assert results[0].status == STATUS_FINDINGS
        slug = f"feat_my-branch_{sha[:7]}"
        assert results[0].change.slug == slug
        assert (config.results_dir / f"gerrit-review-{slug}.json").is_file()
        summary = json.loads(
            (config.results_dir / "summary.json").read_text())
        assert summary[slug]["local"] is True
        assert summary[slug]["ref_name"] == "feat/my-branch"
        assert summary[slug]["number"] is None
        # Markdown report named by ref+sha (no Gerrit number/ps)
        md = (config.results_dir / "markdown" /
              f"{slug}_local_subject.md")
        assert md.is_file()
        assert md.read_text().startswith(
            "# feat/my-branch — local subject")
        assert summary[slug]["markdown"] == f"markdown/{md.name}"
        # worktree cleaned up; repo untouched
        assert not any((tmp_path / "worktrees").glob("kreview_*"))
        assert not (repo / "gerrit-review.json").exists()

    def test_local_in_place(self, repo, tmp_path, stub_claude):
        from lreview.gerrit import LocalChange
        sha = _commit_with_marker(
            repo, "HAS_FINDINGS", json.dumps(REVIEW_SPEC))
        _git(repo, "checkout", "-q", sha)
        # a stale artifact from an old manual run must not be collected
        (repo / "gerrit-review.json").write_text('{"message": "STALE"}')

        change = LocalChange(ref_name="HEAD", sha=sha, subject="s")
        config = _config(repo, tmp_path)
        results = run_batch(config, [change], in_place=True)

        assert results[0].status == STATUS_FINDINGS
        collected = json.loads(
            (config.results_dir /
             f"gerrit-review-{change.slug}.json").read_text())
        assert collected == REVIEW_SPEC  # fresh, not the stale file
        stale = list(config.results_dir.glob("stale-*gerrit-review.json"))
        assert len(stale) == 1
        assert "STALE" in stale[0].read_text()
        # no worktrees were made; repo artifacts cleaned afterwards
        assert not (tmp_path / "worktrees").exists()
        assert not (repo / "gerrit-review.json").exists()
        assert not (repo / "review-metadata.json").exists()
        # Markdown report for the in-place local review
        md = (config.results_dir / "markdown" /
              f"HEAD_{sha[:7]}_s.md")
        assert md.is_file()
        assert "local review — not tied to a Gerrit change" in md.read_text()

    def test_memory_prompt_and_update_tracking(self, repo, tmp_path,
                                               stub_claude):
        """With memory_db set: the prompt names the memory doc, and
        an unchanged doc is flagged as not updated."""
        from lreview.runner import review_prompt
        sha = _git(repo, "rev-parse", "HEAD")
        change = _change(701, sha)
        config = _config(repo, tmp_path, memory_db=tmp_path / "db")

        prompt = review_prompt(config, change)
        assert "memory-prompt.md" in prompt
        doc = tmp_path / "db" / "701-change_701.md"
        assert str(doc) in prompt
        assert doc.is_file()  # skeleton pre-created

        # The stub claude never touches the doc -> not updated
        results = run_batch(config, [change])
        assert results[0].memory_path == doc
        assert results[0].memory_updated is False
        summary = json.loads(
            (config.results_dir / "summary.json").read_text())
        assert summary["701"]["memory"] == str(doc)

    def test_memory_updated_detected(self, repo, tmp_path, stub_claude,
                                     monkeypatch):
        """A review that rewrites its memory doc is detected. The stub
        writes the doc when MEMDOC_FILE names it."""
        import stat as stat_mod
        sha = _git(repo, "rev-parse", "HEAD")
        change = _change(702, sha)
        db = tmp_path / "db"
        doc = db / "702-change_702.md"

        # extend the stub: also write the memory doc
        stub = tmp_path / "bin" / "claude"
        stub.write_text(STUB_CLAUDE.replace(
            'echo \'{"type":"system","subtype":"estimated_tokens"',
            'if [ -n "$MEMDOC_FILE" ]; then echo notes > "$MEMDOC_FILE"; fi\n'
            'echo \'{"type":"system","subtype":"estimated_tokens"'))
        stub.chmod(stub.stat().st_mode | stat_mod.S_IEXEC)
        monkeypatch.setenv("MEMDOC_FILE", str(doc))

        config = _config(repo, tmp_path, memory_db=db)
        results = run_batch(config, [change])
        assert results[0].memory_path == doc
        assert results[0].memory_updated is True
        assert doc.read_text().strip() == "notes"

    def test_no_memory_without_flag(self, repo, tmp_path, stub_claude):
        from lreview.runner import review_prompt
        sha = _git(repo, "rev-parse", "HEAD")
        change = _change(703, sha)
        config = _config(repo, tmp_path)  # memory_db not set

        assert "memory" not in review_prompt(config, change)
        results = run_batch(config, [change])
        assert results[0].memory_path is None
        assert not (tmp_path / "db").exists()

    def test_summary_merges_previous_runs(self, repo, tmp_path, stub_claude):
        sha = _git(repo, "rev-parse", "HEAD")
        config = _config(repo, tmp_path)
        run_batch(config, [_change(601, sha)])
        run_batch(config, [_change(602, sha)])
        summary = json.loads(
            (config.results_dir / "summary.json").read_text())
        assert set(summary) == {"601", "602"}


class TestUpdateSummary:

    def _result(self, number, sha, status=STATUS_FINDINGS, ps=2):
        from lreview.runner import ReviewResult
        change = ResolvedChange(
            number=number, project="p", subject="s", sha=sha,
            patchset=ps, ref="r", base_url="https://gerrit.invalid")
        return ReviewResult(change, status, findings=1)

    def test_posted_survives_same_sha_rereview(self, tmp_path):
        update_summary(tmp_path, [self._result(700, "a" * 40)])
        summary = json.loads((tmp_path / "summary.json").read_text())
        summary["700"]["posted"] = True
        summary["700"]["posted_at"] = "2026-01-01T00:00:00+00:00"
        (tmp_path / "summary.json").write_text(json.dumps(summary))

        update_summary(tmp_path, [self._result(700, "a" * 40)])
        summary = json.loads((tmp_path / "summary.json").read_text())
        assert summary["700"]["posted"] is True
        assert summary["700"]["posted_at"] == "2026-01-01T00:00:00+00:00"

    def test_new_patchset_resets_posted_keeps_history(self, tmp_path):
        update_summary(tmp_path, [self._result(701, "a" * 40, ps=2)])
        summary = json.loads((tmp_path / "summary.json").read_text())
        summary["701"]["posted"] = True
        summary["701"]["posted_at"] = "2026-01-01T00:00:00+00:00"
        (tmp_path / "summary.json").write_text(json.dumps(summary))

        update_summary(tmp_path, [self._result(701, "b" * 40, ps=3)])
        summary = json.loads((tmp_path / "summary.json").read_text())
        assert summary["701"]["posted"] is False
        assert summary["701"]["last_posted"]["sha"] == "a" * 40
        assert summary["701"]["last_posted"]["patchset"] == 2

    def test_failed_rereview_keeps_posted_history(self, tmp_path):
        update_summary(tmp_path, [self._result(702, "a" * 40, ps=2)])
        summary = json.loads((tmp_path / "summary.json").read_text())
        summary["702"]["posted"] = True
        (tmp_path / "summary.json").write_text(json.dumps(summary))

        update_summary(
            tmp_path,
            [self._result(702, "b" * 40, status=STATUS_FAILED, ps=3)])
        summary = json.loads((tmp_path / "summary.json").read_text())
        assert summary["702"]["status"] == STATUS_FAILED
        assert summary["702"]["last_posted"]["sha"] == "a" * 40

    def test_corrupt_summary_backed_up_not_wiped(self, tmp_path, capsys):
        (tmp_path / "summary.json").write_text("{truncated")
        update_summary(tmp_path, [self._result(703, "a" * 40)])
        summary = json.loads((tmp_path / "summary.json").read_text())
        assert "703" in summary
        backups = list(tmp_path.glob("summary.json.corrupt-*"))
        assert len(backups) == 1
        assert backups[0].read_text() == "{truncated"
