"""Post collected kreview results to Gerrit via gerrit-cli.

Posting is pinned to the revision SHA that was actually reviewed (from
the summary manifest), so a patchset pushed while the review was running
gets the comments on the reviewed patchset, not silently on the new one.

Each entry is posted under the manifest lock with a fresh re-read of
its state, so concurrent lreview invocations can neither
double-post a review nor clobber each other's manifest updates.
"""

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .manifest import locked_summary, read_summary
from .runner import STATUS_FINDINGS

DEFAULT_TAG = "autogenerated:ai-review"

DEFAULT_PREFIX = "[AI review - <model>]"


def resolve_prefix(prefix: Optional[str], entry: dict) -> Optional[str]:
    """Resolve the message prefix for an entry.

    None falls back to DEFAULT_PREFIX; a literal "<model>" placeholder
    (default or custom, e.g. "[Marc Bot - AI review - <model>]") is
    replaced with the model that ran the review, falling back to the
    agent name when no model is known.
    """
    if prefix is None:
        prefix = DEFAULT_PREFIX
    model = entry.get("model") or entry.get("agent") or "AI"
    return prefix.replace("<model>", model)


@dataclass
class PostOutcome:
    number: object  # change number, or the slug for local reviews
    status: str  # posted | skipped | error
    detail: str = ""


def load_summary(results_dir: Path) -> dict:
    summary_path = results_dir / "summary.json"
    if not summary_path.is_file():
        raise FileNotFoundError(
            f"{summary_path} not found — run 'lreview run' first")
    return read_summary(results_dir)


def _post_one(results_dir: Path, entry: dict, prefix: Optional[str]):
    """Post a single review; returns (success, detail, prefix used).

    prefix=None auto-stamps the default "[AI review - <model>]"; pass
    an empty string to post without any prefix.
    """
    from gerrit_cli.client import GerritCommentsClient
    from gerrit_cli.reviewer import CodeReviewer

    prefix = resolve_prefix(prefix, entry)

    json_path = results_dir / entry["json"]
    spec = json.loads(json_path.read_text())

    # Post to the Gerrit host the change was reviewed from, not
    # whatever $GERRIT_URL happens to point at.
    client = None
    if entry.get("base_url"):
        client = GerritCommentsClient(url=entry["base_url"])
    reviewer = CodeReviewer(client=client)

    result = reviewer.post_review(
        change_number=entry["number"],
        comments=spec.get("comments"),
        message=spec.get("message"),
        vote=spec.get("vote"),
        revision=entry["sha"],
        prefix=prefix,
        tag=spec.get("tag") or DEFAULT_TAG,
    )
    if result.success:
        detail = (f"{result.comments_posted} comment(s) on "
                  f"ps{entry['patchset']}")
        if prefix:
            detail += f" as '{prefix}'"
        return True, detail, prefix
    return False, result.error or "unknown error", prefix


def post_results(
    results_dir: Path,
    changes: Optional[list[int]] = None,
    prefix: Optional[str] = None,
    force: bool = False,
) -> list[PostOutcome]:
    """Post reviews with findings to Gerrit.

    Args:
        results_dir: Directory holding summary.json and review files.
        changes: Change numbers to post; None posts every unposted
            review with findings.
        prefix: Text prepended to every message. None auto-stamps
            "[AI review - <model>]"; "" posts without a prefix.
        force: Post even if the manifest says it was already posted.
    """
    snapshot = load_summary(results_dir)
    if changes:
        wanted = [str(n) for n in changes]
        missing = [n for n in wanted if n not in snapshot]
        if missing:
            raise KeyError(
                f"change(s) {', '.join(missing)} not found in "
                f"{results_dir}/summary.json")
    else:
        wanted = list(snapshot.keys())

    outcomes: list[PostOutcome] = []
    for key in wanted:
        # Re-read and post under the manifest lock: the guard and the
        # posted-flag update are atomic against concurrent invocations.
        with locked_summary(results_dir) as summary:
            entry = summary.get(key)
            if entry is None:
                outcomes.append(PostOutcome(
                    int(key), "skipped", "no longer in manifest"))
                continue
            number = entry["number"]

            if entry.get("local"):
                outcomes.append(PostOutcome(
                    key, "skipped",
                    "local review — not tied to a Gerrit change"))
                continue
            if entry["status"] != STATUS_FINDINGS:
                outcomes.append(PostOutcome(
                    number, "skipped", f"status is '{entry['status']}'"))
                continue
            if entry.get("posted") and not force:
                outcomes.append(PostOutcome(
                    number, "skipped",
                    "already posted (use --force to repost)"))
                continue

            try:
                success, detail, used_prefix = _post_one(
                    results_dir, entry, prefix)
            except Exception as exc:  # noqa: BLE001 - one bad entry
                # (missing file, config error) must not kill the rest
                outcomes.append(PostOutcome(number, "error", str(exc)))
                continue

            if success:
                entry["posted"] = True
                entry["posted_at"] = datetime.now(timezone.utc).isoformat(
                    timespec="seconds")
                entry["posted_prefix"] = used_prefix
                outcomes.append(PostOutcome(number, "posted", detail))
            else:
                outcomes.append(PostOutcome(number, "error", detail))

    return outcomes
