"""Live check of the graph's Stats numbers against Gerrit.

Builds a real graph, fetches the same changes raw, and recomputes every
per-change time and headline number with code independent of the graph
package: its own timestamp and message parsing, a hand-classified bot
list, and the stdlib statistics module. Events after the build instant
are ignored, so activity between the build and the refetch is harmless.

    pytest -m integration gerrit_cli/tests/test_graph_summary_live.py
"""

import re
import statistics
from datetime import datetime, timezone
from urllib.parse import quote

import pytest

from gerrit_cli import GerritCommentsClient
from gerrit_cli.graph import build_graph, resolve_ticket_anchor

pytestmark = pytest.mark.integration

# Ticket-mode graph, as `gc graph LU-18222`: merged, open and abandoned
# patches, about 20 changes.
TICKET = "LU-18222"
DAY = 86400
BOTS = {
    "Maloo", "Lustre Gerrit Janitor", "jenkins", "Jenkins", "wc-checkpatch",
    "Misc Code Checks Robot (Gatekeeper helper)", "Autotest",
    "Lustre RISC-V Builder", "Gerrit AI review for Lustre", "Janitor Bot",
}


def _ep(s):
    return int(datetime.strptime(s[:19], "%Y-%m-%d %H:%M:%S")
               .replace(tzinfo=timezone.utc).timestamp())


def _person(name):
    return name.split(" (")[0] if name.endswith(")") else name


def _notice(text):
    first = text.split("\n")[0].strip()
    for word in ("Abandoned", "Restored"):
        if first == word or first.startswith(word + " "):
            return word
    starts = ("Uploaded patch set ", "Change has been successfully",
              "Removed the following votes", "Removed reviewer", "Removed cc")
    if first.startswith(starts) or re.fullmatch(
            r"Patch Set \d+: Patch Set \d+ was rebased.*", first):
        return "notice"
    return None


def _tool_note(text):
    lines = [ln.strip() for ln in text.split("\n") if ln.strip()]
    if lines and lines[0].startswith("Patch Set "):
        lines = lines[1:]
    if lines and re.fullmatch(r"\(\d+ comments?\)", lines[0]):
        lines = lines[1:]
    if not lines or not lines[0].lstrip("*").startswith("["):
        return False
    label = lines[0].lstrip("*")[1:].split("]")[0]
    return label.startswith("AI review") or label.endswith("Bot")


def _replay(ch, as_of):
    """The change as it stood at `as_of`."""
    revs = sorted((r["_number"], _ep(r["created"]))
                  for r in ch["revisions"].values())
    revs = [(n, t) for n, t in revs if t <= as_of]
    abandoned, reviews, reviewers = None, [], {}
    for m in ch.get("messages", []):
        t = _ep(m["date"])
        if t > as_of:
            continue
        tag = m.get("tag") or ""
        text = (m.get("message") or "").strip()
        kind = None if tag else _notice(text)
        if tag == "autogenerated:gerrit:abandon" or kind == "Abandoned":
            abandoned = t
        elif tag == "autogenerated:gerrit:restore" or kind == "Restored":
            abandoned = None
        elif not tag.startswith("autogenerated:") and not kind:
            who = (m.get("author") or {}).get("name")
            if (who and who not in BOTS and not _tool_note(text)
                    and _person(who) != _person(ch["owner"]["name"])):
                reviews.append(t)
                reviewers[who] = reviewers.get(who, 0) + 1
    reviews.sort()
    opened = _ep(ch["created"])
    if ch["status"] == "MERGED" and _ep(ch["submitted"]) <= as_of:
        status, closed = "MERGED", max(opened, _ep(ch["submitted"]))
    elif ch["status"] == "ABANDONED" and abandoned is not None:
        status, closed = "ABANDONED", max(opened, abandoned)
    else:
        status, closed = "NEW", None
    return {
        "status": status, "opened": opened, "closed": closed,
        "ps": revs[-1][0], "last": max([revs[-1][1]] + reviews[-1:]),
        "first_review": next((t for t in reviews if t >= opened), None),
        "reviewers": reviewers,
    }


def _p90(vals):
    if len(vals) == 1:
        return vals[0]
    return statistics.quantiles(vals, n=10, method="inclusive")[8]


@pytest.fixture(scope="module")
def graph_and_replay():
    client = GerritCommentsClient()
    base = client.url.rstrip("/")
    anchor = resolve_ticket_anchor(client, TICKET)
    g = build_graph(client, anchor, base, progress=False,
                    extra_tickets=[TICKET])
    as_of = g["stats"]["summary"]["as_of"]
    ids = [n["id"] for n in g["nodes"] if not n.get("trunk_structural")]
    raw = {}
    for i in range(0, len(ids), 25):
        q = " OR ".join(f"change:{c}" for c in ids[i:i + 25])
        for ch in client.rest.get(
                f"/changes/?q={quote(q, safe=':+ ')}&o=ALL_REVISIONS"
                "&o=MESSAGES&o=DETAILED_ACCOUNTS&n=100"):
            raw[ch["_number"]] = ch
    return g, {cn: _replay(raw[cn], as_of) for cn in ids}


def test_per_change_times_match_gerrit(graph_and_replay):
    g, replay = graph_and_replay
    nodes = {n["id"]: n for n in g["nodes"]}
    for cn, v in replay.items():
        n = nodes[cn]
        got = (n["status"], n["opened_at"], n["closed_at"], n["last_activity"],
               n["first_review_at"], n["reviewers"], n["current_patchset"])
        want = (v["status"], v["opened"], v["closed"], v["last"],
                v["first_review"], v["reviewers"], v["ps"])
        assert got == want, cn


def test_headline_numbers_match_gerrit(graph_and_replay):
    g, replay = graph_and_replay
    s = g["stats"]["summary"]
    as_of = s["as_of"]
    recs = list(replay.items())
    of = lambda st: [(cn, v) for cn, v in recs if v["status"] == st]
    assert of("NEW") and of("MERGED") and of("ABANDONED"), "fixture lost a status"
    assert (s["patches"], s["open"], s["merged"], s["abandoned"]) == (
        len(recs), len(of("NEW")), len(of("MERGED")), len(of("ABANDONED")))

    d30, d60 = as_of - 30 * DAY, as_of - 60 * DAY
    events = {
        "opened": [v["opened"] for _, v in recs],
        "merged": [v["closed"] for _, v in of("MERGED")],
        "abandoned": [v["closed"] for _, v in of("ABANDONED")],
    }
    for key, ts in events.items():
        assert s["last_30d"][key] == sum(d30 < t <= as_of for t in ts), key
        assert s["prev_30d"][key] == sum(d60 < t <= d30 for t in ts), key
        assert s["recent_events"][key] == sorted(
            t for t in ts if d60 < t <= as_of), key
    assert s["open_30d_ago"] == sum(
        v["opened"] <= d30 and (v["closed"] is None or v["closed"] > d30)
        for _, v in recs)

    ttm = sorted(v["closed"] - v["opened"] for _, v in of("MERGED"))
    assert s["time_to_merge"]["count"] == len(ttm)
    assert abs(s["time_to_merge"]["median"] - statistics.median(ttm)) <= 1
    assert abs(s["time_to_merge"]["p90"] - _p90(ttm)) <= 1
    ttr = sorted(v["first_review"] - v["opened"] for _, v in recs
                 if v["first_review"] is not None)
    assert s["time_to_first_review"]["count"] == len(ttr)
    assert abs(s["time_to_first_review"]["median"] - statistics.median(ttr)) <= 1
    assert abs(s["time_to_first_review"]["p90"] - _p90(ttr)) <= 1
    ps = [v["ps"] for _, v in of("MERGED")]
    assert s["patchsets_to_merge"]["median"] == statistics.median(ps)
    assert s["patchsets_to_merge"]["max"] == max(ps)

    order = [cn for cn, _ in recs]
    first = lambda key: min(of("NEW"), key=lambda x: (x[1][key], order.index(x[0])))[0]
    assert s["oldest_open"]["id"] == first("opened")
    assert s["longest_idle"]["id"] == first("last")

    months = {}
    for _, v in of("MERGED"):
        k = datetime.fromtimestamp(v["closed"], tz=timezone.utc).strftime("%Y-%m")
        months[k] = months.get(k, 0) + 1
    assert s["merged_by_month"] == [[m, months.get(m, 0)] for m, _ in s["merged_by_month"]]
    assert s["merged_by_month"][-1][0] == datetime.fromtimestamp(
        as_of, tz=timezone.utc).strftime("%Y-%m")
