"""Activity data behind the graph's Stats tab: change creation and
patchset upload times from the revision payload, human review events
and the abandon time from change messages."""

from gerrit_cli.graph.nodes import _make_node, _update_node_meta, gerrit_epoch
from gerrit_cli.graph.review import _extract_activity, _is_bot_account


def _msg(date, author, text="Patch Set 1:", tag=None):
    m = {"date": date, "author": {"name": author}, "message": text}
    if tag:
        m["tag"] = tag
    return m


class TestGerritEpoch:
    def test_parses_utc(self):
        assert gerrit_epoch("1970-01-02 00:00:00.000000000") == 86400

    def test_unparsable_is_zero(self):
        assert gerrit_epoch("") == 0
        assert gerrit_epoch("yesterday") == 0


class TestUpdateNodeMetaActivity:
    def _change(self, revs, created="2026-01-01 10:00:00.000000000"):
        return {
            "created": created,
            "revisions": {
                f"h{ps}": {"_number": ps, "created": t} for ps, t in revs
            },
        }

    def test_created_and_ps_times_in_patchset_order(self):
        node = _make_node(1, "LU-1 x", "NEW", 3, "a", "https://g")
        _update_node_meta(node, self._change([
            (3, "2026-01-03 00:00:00.000000000"),
            (1, "2026-01-01 10:00:00.000000000"),
            (2, "2026-01-02 00:00:00.000000000"),
        ]))
        assert node["created"] == "2026-01-01 10:00:00.000000000"
        assert node["ps_times"] == [
            gerrit_epoch("2026-01-01 10:00:00"),
            gerrit_epoch("2026-01-02 00:00:00"),
            gerrit_epoch("2026-01-03 00:00:00"),
        ]

    def test_current_revision_payload_does_not_truncate_history(self):
        node = _make_node(1, "LU-1 x", "NEW", 3, "a", "https://g")
        _update_node_meta(node, self._change([
            (1, "2026-01-01 00:00:00.0"), (2, "2026-01-02 00:00:00.0"),
        ]))
        _update_node_meta(node, self._change([(2, "2026-01-02 00:00:00.0")]))
        assert len(node["ps_times"]) == 2


class TestExtractActivity:
    def test_human_non_owner_messages_are_reviews(self):
        msgs = [
            _msg("2026-01-01 10:00:00.0", "Owner", "Uploaded patch set 1.",
                 tag="autogenerated:gerrit:newPatchSet"),
            _msg("2026-01-01 10:05:00.0", "Maloo"),
            _msg("2026-01-01 10:06:00.0", "Lustre RISC-V Builder"),
            _msg("2026-01-01 10:07:00.0", "Misc Code Checks Robot (Gatekeeper helper)"),
            _msg("2026-01-02 09:00:00.0", "Andreas Dilger", "Patch Set 1: Code-Review-1"),
            _msg("2026-01-02 12:00:00.0", "Owner", "Patch Set 1: (1 comment)"),
            _msg("2026-01-03 09:00:00.0", "Andreas Dilger", "Patch Set 2: Code-Review+1"),
            _msg("2026-01-03 10:00:00.0", "Oleg Drokin", "Patch Set 2: Code-Review+1"),
            _msg("2026-01-03 11:00:00.0", "Someone", "AI review",
                 tag="autogenerated:ai-review"),
        ]
        act = _extract_activity(msgs, "Owner")
        assert act["reviewers"] == {"Andreas Dilger": 2, "Oleg Drokin": 1}
        assert act["review_times"] == sorted(act["review_times"])
        assert act["review_times"][0] == gerrit_epoch("2026-01-02 09:00:00")
        assert act["abandoned_at"] == ""

    def test_abandon_then_restore_clears(self):
        msgs = [
            _msg("2026-01-05 00:00:00.0", "O", "Abandoned", tag="autogenerated:gerrit:abandon"),
            _msg("2026-01-06 00:00:00.0", "O", "Restored", tag="autogenerated:gerrit:restore"),
        ]
        assert _extract_activity(msgs, "O")["abandoned_at"] == ""

    def test_last_abandon_wins(self):
        msgs = [
            _msg("2026-01-05 00:00:00.0", "O", "Abandoned", tag="autogenerated:gerrit:abandon"),
            _msg("2026-01-06 00:00:00.0", "O", "Restored", tag="autogenerated:gerrit:restore"),
            _msg("2026-01-09 00:00:00.0", "O", "Abandoned", tag="autogenerated:gerrit:abandon"),
        ]
        assert _extract_activity(msgs, "O")["abandoned_at"] == "2026-01-09 00:00:00.0"

    def test_bot_detection(self):
        for bot in ("Maloo", "jenkins", "Janitor Bot", "Lustre Gerrit Janitor",
                    "wc-checkpatch", "Autotest", "Lustre RISC-V Builder"):
            assert _is_bot_account(bot), bot
        for human in ("Andreas Dilger", "Oleg Drokin", "Robert Read", "kg.xu"):
            assert not _is_bot_account(human), human

    def test_legacy_untagged_notices_are_not_reviews(self):
        # 2019-era changes carry Gerrit's own notices without a tag.
        msgs = [
            _msg("2019-08-13 00:00:00.0", "Co Author", "Uploaded patch set 3."),
            _msg("2019-08-14 00:00:00.0", "Andreas Dilger",
                 "Removed the following votes:\n\n* Code-Review-1 by X"),
            _msg("2019-08-15 00:00:00.0", "Oleg Drokin",
                 "Change has been successfully merged by Oleg Drokin"),
            _msg("2019-08-16 00:00:00.0", "Andreas Dilger", "Patch Set 3: Code-Review+1"),
        ]
        act = _extract_activity(msgs, "Owner")
        assert act["reviewers"] == {"Andreas Dilger": 1}
        assert act["review_times"] == [gerrit_epoch("2019-08-16 00:00:00")]

    def test_legacy_untagged_abandon_and_restore(self):
        abandoned = [_msg("2019-08-26 06:54:22.0", "Wang Shilong", "Abandoned")]
        assert _extract_activity(abandoned, "Wang Shilong")["abandoned_at"] == "2019-08-26 06:54:22.0"
        restored = abandoned + [_msg("2019-09-01 00:00:00.0", "Wang Shilong", "Restored")]
        assert _extract_activity(restored, "Wang Shilong")["abandoned_at"] == ""
        # A reviewer saying "Abandoning ..." is a review, not an abandon.
        chat = [_msg("2019-08-26 00:00:00.0", "Andreas Dilger", "Abandoning this is fine")]
        act = _extract_activity(chat, "Wang Shilong")
        assert act["abandoned_at"] == "" and act["reviewers"] == {"Andreas Dilger": 1}

    def test_tool_notes_through_a_person_are_not_reviews(self):
        msgs = [
            _msg("2026-09-21 00:00:00.0", "Marc Vef",
                 "Patch Set 26:\n\n[Marc Bot] Note: This change has been cherry-picked"),
            _msg("2026-09-22 00:00:00.0", "Marc Vef",
                 "Patch Set 26:\n\n(2 comments)\n\n**[AI review - opus]**\n\nFindings"),
            _msg("2026-09-23 00:00:00.0", "Marc Vef",
                 "Patch Set 26: Code-Review+1\n\n[typo] fixed, thanks"),
        ]
        act = _extract_activity(msgs, "Owner")
        assert act["reviewers"] == {"Marc Vef": 1}
        assert act["review_times"] == [gerrit_epoch("2026-09-23 00:00:00")]

    def test_owner_second_account_is_the_owner(self):
        msgs = [
            _msg("2023-01-17 00:00:00.0", "Patrick Farrell", "Patch Set 1:"),
            _msg("2023-01-18 00:00:00.0", "Patrick Farrel", "Patch Set 1: Code-Review+1"),
        ]
        act = _extract_activity(msgs, "Patrick Farrell (personal)")
        assert act["reviewers"] == {"Patrick Farrel": 1}

    def test_ai_review_account_is_a_bot(self):
        assert _is_bot_account("Gerrit AI review for Lustre")
